/*
 * Copyright (c) 2024 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 将 T_cross 落盘为带 commonlibrary 风格 @tc.* 注释的 .test.js 分片。
 *
 * 布局：
 *   out/test/suite_v2/generated/
 *     catalog.json          # 共享场景表（只写一份）
 *     summary.json
 *     parse/chunk_XXXX.test.js
 *     gen/chunk_XXXX.test.js
 *     integration/chunk_XXXX.test.js
 *
 * 分片内每条 test 上方有完整 @tc 注释；场景体通过 catalog[index] 引用，避免 3 份重复拷贝。
 *
 * 用法：node ./out/test/suite_v2/tools/generate_b1.js
 * 可选：SUITE_V2_GENERATE_LIMIT=N 只生成前 N 条/套（调试）
 */

import * as fs from 'fs';
import * as path from 'path';
import { getTCross } from '../catalog/expand';
import { Scenario, SuiteKind } from '../catalog/types';
import { buildTcMeta, formatTcComment } from '../harness/tc_meta';

const CHUNK = 1000;

function outRoot(): string {
  return path.resolve(__dirname, '../generated');
}

function emitChunk(
  suiteKind: SuiteKind,
  dirName: string,
  runnerExpr: string,
  start: number,
  slice: Scenario[],
  catalogRel: string
): void {
  const lines: string[] = [];
  lines.push(`/* Auto-generated by suite_v2/tools/generate_b1.ts — do not edit */`);
  lines.push(`const { ${runnerExpr} } = require('../../harness/runners');`);
  lines.push(`const CATALOG = require('${catalogRel}');`);
  lines.push(`suite('SuiteV2_${suiteKind}_generated_${start}', function () {`);
  lines.push(`  this.timeout(30000);`);

  slice.forEach((sc, offset) => {
    const index = start + offset;
    const meta = buildTcMeta(suiteKind, sc, index);
    // 转义 test 名中的引号（typeId 一般无引号）
    const safeName = meta.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    lines.push(formatTcComment(meta));
    lines.push(`  test('${safeName}', function () {`);
    lines.push(`    ${runnerExpr}(CATALOG[${index}]);`);
    lines.push(`  });`);
    lines.push('');
  });

  lines.push(`});`);
  lines.push('');

  const dir = path.join(outRoot(), dirName);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `chunk_${String(Math.floor(start / CHUNK)).padStart(4, '0')}.test.js`);
  fs.writeFileSync(file, lines.join('\n'), 'utf8');
}

function emitSuite(suiteKind: SuiteKind, dirName: string, runnerExpr: string, all: Scenario[]): number {
  // catalog.json 在 generated/ 根；分片在 generated/{dir}/ → ../catalog.json
  const catalogRel = '../catalog.json';
  for (let i = 0; i < all.length; i += CHUNK) {
    emitChunk(suiteKind, dirName, runnerExpr, i, all.slice(i, i + CHUNK), catalogRel);
    if ((i / CHUNK) % 20 === 0) {
      process.stdout.write(`[generate] ${suiteKind} ${i}/${all.length}\r`);
    }
  }
  console.log(`[generate] ${suiteKind} done: ${all.length}`);
  return all.length;
}

function main(): void {
  const root = outRoot();
  if (fs.existsSync(root)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
  fs.mkdirSync(root, { recursive: true });

  let all = getTCross();
  const limitRaw = process.env.SUITE_V2_GENERATE_LIMIT;
  if (limitRaw) {
    const n = Math.max(1, parseInt(limitRaw, 10) || 1000);
    all = all.slice(0, n);
    console.log(`[generate] SUITE_V2_GENERATE_LIMIT=${n}`);
  }

  console.log(`[generate] writing catalog.json (${all.length} scenarios)...`);
  fs.writeFileSync(path.join(root, 'catalog.json'), JSON.stringify(all), 'utf8');

  const p = emitSuite('P', 'parse', 'runParseCase', all);
  const g = emitSuite('G', 'gen', 'runGenCase', all);
  const i = emitSuite('I', 'integration', 'runIntegCase', all);
  const summary = {
    P: p,
    G: g,
    I: i,
    total: p + g + i,
    chunkSize: CHUNK,
    catalog: 'catalog.json',
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(root, 'summary.json'), JSON.stringify(summary, null, 2), 'utf8');
  // 占位，避免空目录被忽略
  fs.writeFileSync(path.join(root, '.generated'), 'ok\n', 'utf8');
  console.log('[suite_v2:generate] wrote', summary);
}

main();
