/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_str_as_param', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RAW_NORM_000225
   * @tc.name testInteg_PRI_str_PAR_RAW_NORM_000225
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RAW.NORM.V0
   */
  it('testInteg_PRI_str_PAR_RAW_NORM_000225', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RAW.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RAW_BOUND_000226
   * @tc.name testInteg_PRI_str_PAR_RAW_BOUND_000226
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RAW.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_RAW_BOUND_000226', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RAW.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RAW_ERR_000227
   * @tc.name testInteg_PRI_str_PAR_RAW_ERR_000227
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.RAW.ERR.V0
   */
  it('testInteg_PRI_str_PAR_RAW_ERR_000227', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RAW_SPEC_000228
   * @tc.name testInteg_PRI_str_PAR_RAW_SPEC_000228
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RAW.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_RAW_SPEC_000228', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RAW.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_OPT_NORM_000229
   * @tc.name testInteg_PRI_str_PAR_OPT_NORM_000229
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.OPT.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.OPT.NORM.V0
   */
  it('testInteg_PRI_str_PAR_OPT_NORM_000229', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.OPT.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_OPT_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.OPT.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.OPT.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.OPT.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_OPT_BOUND_000230
   * @tc.name testInteg_PRI_str_PAR_OPT_BOUND_000230
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.OPT.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.OPT.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_OPT_BOUND_000230', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.OPT.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_OPT_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.OPT.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.OPT.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.OPT.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_OPT_ERR_000231
   * @tc.name testInteg_PRI_str_PAR_OPT_ERR_000231
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.OPT.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.OPT.ERR.V0
   */
  it('testInteg_PRI_str_PAR_OPT_ERR_000231', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.OPT.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_OPT_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.OPT.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_OPT_SPEC_000232
   * @tc.name testInteg_PRI_str_PAR_OPT_SPEC_000232
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.OPT.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.OPT.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_OPT_SPEC_000232', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.OPT.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_OPT_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.OPT.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.OPT.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.OPT.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RO_NORM_000233
   * @tc.name testInteg_PRI_str_PAR_RO_NORM_000233
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RO.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RO.NORM.V0
   */
  it('testInteg_PRI_str_PAR_RO_NORM_000233', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RO.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RO_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RO.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RO.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RO.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RO_BOUND_000234
   * @tc.name testInteg_PRI_str_PAR_RO_BOUND_000234
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RO.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RO.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_RO_BOUND_000234', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RO.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RO_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RO.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RO.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RO.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RO_ERR_000235
   * @tc.name testInteg_PRI_str_PAR_RO_ERR_000235
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RO.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.RO.ERR.V0
   */
  it('testInteg_PRI_str_PAR_RO_ERR_000235', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.RO.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RO_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.RO.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_RO_SPEC_000236
   * @tc.name testInteg_PRI_str_PAR_RO_SPEC_000236
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.RO.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.RO.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_RO_SPEC_000236', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.RO.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_RO_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.RO.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.RO.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.RO.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PTR_NORM_000237
   * @tc.name testInteg_PRI_str_PAR_PTR_NORM_000237
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PTR.NORM.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PTR.NORM.V0
   */
  it('testInteg_PRI_str_PAR_PTR_NORM_000237', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PTR.NORM.V0 input=string*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PTR.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string*");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PTR_BOUND_000238
   * @tc.name testInteg_PRI_str_PAR_PTR_BOUND_000238
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PTR.BOUND.V0 input="string *" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PTR.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_PTR_BOUND_000238', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string *";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PTR.BOUND.V0 input=string *");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PTR.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string *");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PTR_ERR_000239
   * @tc.name testInteg_PRI_str_PAR_PTR_ERR_000239
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.PTR.ERR.V0
   */
  it('testInteg_PRI_str_PAR_PTR_ERR_000239', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.PTR.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PTR_SPEC_000240
   * @tc.name testInteg_PRI_str_PAR_PTR_SPEC_000240
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PTR.SPEC.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PTR.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_PTR_SPEC_000240', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PTR.SPEC.V0 input=string*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PTR.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string*");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_ARR1_NORM_000241
   * @tc.name testInteg_PRI_str_PAR_ARR1_NORM_000241
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.ARR1.NORM.V0
   */
  it('testInteg_PRI_str_PAR_ARR1_NORM_000241', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.PAR.ARR1.NORM.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<string>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.PAR.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_ARR1_BOUND_000242
   * @tc.name testInteg_PRI_str_PAR_ARR1_BOUND_000242
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.ARR1.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_ARR1_BOUND_000242', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.PAR.ARR1.BOUND.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<string>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.PAR.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_ARR1_ERR_000243
   * @tc.name testInteg_PRI_str_PAR_ARR1_ERR_000243
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.ARR1.ERR.V0
   */
  it('testInteg_PRI_str_PAR_ARR1_ERR_000243', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_252672969__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_ARR1_SPEC_000244
   * @tc.name testInteg_PRI_str_PAR_ARR1_SPEC_000244
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.ARR1.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_ARR1_SPEC_000244', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< string >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.PAR.ARR1.SPEC.V0 input=std::vector< string >");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<string>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< string >");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.PAR.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_NULLU_NORM_000245
   * @tc.name testInteg_PRI_str_PAR_NULLU_NORM_000245
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.NULLU.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.NULLU.NORM.V0
   */
  it('testInteg_PRI_str_PAR_NULLU_NORM_000245', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.NULLU.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_NULLU_BOUND_000246
   * @tc.name testInteg_PRI_str_PAR_NULLU_BOUND_000246
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.NULLU.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.NULLU.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_NULLU_BOUND_000246', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.NULLU.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_NULLU_ERR_000247
   * @tc.name testInteg_PRI_str_PAR_NULLU_ERR_000247
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.NULLU.ERR.V0
   */
  it('testInteg_PRI_str_PAR_NULLU_ERR_000247', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_NULLU_SPEC_000248
   * @tc.name testInteg_PRI_str_PAR_NULLU_SPEC_000248
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.NULLU.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.NULLU.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_NULLU_SPEC_000248', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.NULLU.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PROM_NORM_000249
   * @tc.name testInteg_PRI_str_PAR_PROM_NORM_000249
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PROM.NORM.V0
   */
  it('testInteg_PRI_str_PAR_PROM_NORM_000249', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PROM.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PROM_BOUND_000250
   * @tc.name testInteg_PRI_str_PAR_PROM_BOUND_000250
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PROM.BOUND.V0
   */
  it('testInteg_PRI_str_PAR_PROM_BOUND_000250', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PROM.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PROM_ERR_000251
   * @tc.name testInteg_PRI_str_PAR_PROM_ERR_000251
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.PAR.PROM.ERR.V0
   */
  it('testInteg_PRI_str_PAR_PROM_ERR_000251', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.PAR.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.PAR.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_PAR_PROM_SPEC_000252
   * @tc.name testInteg_PRI_str_PAR_PROM_SPEC_000252
   * @tc.desc Verify roundtrip parse+map for PRI_str.PAR.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.PAR.PROM.SPEC.V0
   */
  it('testInteg_PRI_str_PAR_PROM_SPEC_000252', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.PAR.PROM.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: string): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_PAR_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.PAR.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.PAR.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.PAR.PROM.SPEC.V0");
  });

});
