/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_str_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_RAW_NORM_000253
   * @tc.name testInteg_PRI_str_RET_RAW_NORM_000253
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.RAW.NORM.V0
   */
  it('testInteg_PRI_str_RET_RAW_NORM_000253', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.RAW.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_RAW_BOUND_000254
   * @tc.name testInteg_PRI_str_RET_RAW_BOUND_000254
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.RAW.BOUND.V0
   */
  it('testInteg_PRI_str_RET_RAW_BOUND_000254', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.RAW.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_RAW_ERR_000255
   * @tc.name testInteg_PRI_str_RET_RAW_ERR_000255
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.RET.RAW.ERR.V0
   */
  it('testInteg_PRI_str_RET_RAW_ERR_000255', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.RET.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_RAW_SPEC_000256
   * @tc.name testInteg_PRI_str_RET_RAW_SPEC_000256
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.RAW.SPEC.V0
   */
  it('testInteg_PRI_str_RET_RAW_SPEC_000256', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.RAW.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PTR_NORM_000257
   * @tc.name testInteg_PRI_str_RET_PTR_NORM_000257
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PTR.NORM.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PTR.NORM.V0
   */
  it('testInteg_PRI_str_RET_PTR_NORM_000257', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PTR.NORM.V0 input=string*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string*");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PTR_BOUND_000258
   * @tc.name testInteg_PRI_str_RET_PTR_BOUND_000258
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PTR.BOUND.V0 input="string *" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PTR.BOUND.V0
   */
  it('testInteg_PRI_str_RET_PTR_BOUND_000258', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string *";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PTR.BOUND.V0 input=string *");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string *");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PTR_ERR_000259
   * @tc.name testInteg_PRI_str_RET_PTR_ERR_000259
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.RET.PTR.ERR.V0
   */
  it('testInteg_PRI_str_RET_PTR_ERR_000259', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.RET.PTR.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PTR_SPEC_000260
   * @tc.name testInteg_PRI_str_RET_PTR_SPEC_000260
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PTR.SPEC.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PTR.SPEC.V0
   */
  it('testInteg_PRI_str_RET_PTR_SPEC_000260', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PTR.SPEC.V0 input=string*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string*");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_ARR1_NORM_000261
   * @tc.name testInteg_PRI_str_RET_ARR1_NORM_000261
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.ARR1.NORM.V0
   */
  it('testInteg_PRI_str_RET_ARR1_NORM_000261', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.RET.ARR1.NORM.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_ARR1_BOUND_000262
   * @tc.name testInteg_PRI_str_RET_ARR1_BOUND_000262
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.ARR1.BOUND.V0
   */
  it('testInteg_PRI_str_RET_ARR1_BOUND_000262', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.RET.ARR1.BOUND.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_ARR1_ERR_000263
   * @tc.name testInteg_PRI_str_RET_ARR1_ERR_000263
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.RET.ARR1.ERR.V0
   */
  it('testInteg_PRI_str_RET_ARR1_ERR_000263', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_252672969__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.RET.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_ARR1_SPEC_000264
   * @tc.name testInteg_PRI_str_RET_ARR1_SPEC_000264
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.ARR1.SPEC.V0
   */
  it('testInteg_PRI_str_RET_ARR1_SPEC_000264', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< string >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.RET.ARR1.SPEC.V0 input=std::vector< string >");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< string >");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_NULLU_NORM_000265
   * @tc.name testInteg_PRI_str_RET_NULLU_NORM_000265
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.NULLU.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.NULLU.NORM.V0
   */
  it('testInteg_PRI_str_RET_NULLU_NORM_000265', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.NULLU.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_NULLU_BOUND_000266
   * @tc.name testInteg_PRI_str_RET_NULLU_BOUND_000266
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.NULLU.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.NULLU.BOUND.V0
   */
  it('testInteg_PRI_str_RET_NULLU_BOUND_000266', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.NULLU.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_NULLU_ERR_000267
   * @tc.name testInteg_PRI_str_RET_NULLU_ERR_000267
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.RET.NULLU.ERR.V0
   */
  it('testInteg_PRI_str_RET_NULLU_ERR_000267', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.RET.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_NULLU_SPEC_000268
   * @tc.name testInteg_PRI_str_RET_NULLU_SPEC_000268
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.NULLU.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.NULLU.SPEC.V0
   */
  it('testInteg_PRI_str_RET_NULLU_SPEC_000268', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.NULLU.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PROM_NORM_000269
   * @tc.name testInteg_PRI_str_RET_PROM_NORM_000269
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PROM.NORM.V0
   */
  it('testInteg_PRI_str_RET_PROM_NORM_000269', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PROM.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PROM_BOUND_000270
   * @tc.name testInteg_PRI_str_RET_PROM_BOUND_000270
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PROM.BOUND.V0
   */
  it('testInteg_PRI_str_RET_PROM_BOUND_000270', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PROM.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PROM_ERR_000271
   * @tc.name testInteg_PRI_str_RET_PROM_ERR_000271
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.RET.PROM.ERR.V0
   */
  it('testInteg_PRI_str_RET_PROM_ERR_000271', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.RET.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_RET_PROM_SPEC_000272
   * @tc.name testInteg_PRI_str_RET_PROM_SPEC_000272
   * @tc.desc Verify roundtrip parse+map for PRI_str.RET.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.RET.PROM.SPEC.V0
   */
  it('testInteg_PRI_str_RET_PROM_SPEC_000272', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.RET.PROM.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.RET.PROM.SPEC.V0");
  });

});
