/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_str_as_typealias', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_RAW_NORM_000273
   * @tc.name testInteg_PRI_str_TAL_RAW_NORM_000273
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.RAW.NORM.V0
   */
  it('testInteg_PRI_str_TAL_RAW_NORM_000273', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.RAW.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.RAW.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_RAW_BOUND_000274
   * @tc.name testInteg_PRI_str_TAL_RAW_BOUND_000274
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.RAW.BOUND.V0
   */
  it('testInteg_PRI_str_TAL_RAW_BOUND_000274', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.RAW.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.RAW.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_RAW_ERR_000275
   * @tc.name testInteg_PRI_str_TAL_RAW_ERR_000275
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.TAL.RAW.ERR.V0
   */
  it('testInteg_PRI_str_TAL_RAW_ERR_000275', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.TAL.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.TAL.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_RAW_SPEC_000276
   * @tc.name testInteg_PRI_str_TAL_RAW_SPEC_000276
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.RAW.SPEC.V0
   */
  it('testInteg_PRI_str_TAL_RAW_SPEC_000276', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.RAW.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.RAW.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_ARR1_NORM_000277
   * @tc.name testInteg_PRI_str_TAL_ARR1_NORM_000277
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.ARR1.NORM.V0
   */
  it('testInteg_PRI_str_TAL_ARR1_NORM_000277', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.TAL.ARR1.NORM.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<string>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.ARR1.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.TAL.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_ARR1_BOUND_000278
   * @tc.name testInteg_PRI_str_TAL_ARR1_BOUND_000278
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.ARR1.BOUND.V0
   */
  it('testInteg_PRI_str_TAL_ARR1_BOUND_000278', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<string>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.TAL.ARR1.BOUND.V0 input=std::vector<string>");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<string>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.ARR1.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<string>");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.TAL.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_ARR1_ERR_000279
   * @tc.name testInteg_PRI_str_TAL_ARR1_ERR_000279
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.TAL.ARR1.ERR.V0
   */
  it('testInteg_PRI_str_TAL_ARR1_ERR_000279', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_252672969__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.TAL.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.TAL.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_ARR1_SPEC_000280
   * @tc.name testInteg_PRI_str_TAL_ARR1_SPEC_000280
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.ARR1.SPEC.V0
   */
  it('testInteg_PRI_str_TAL_ARR1_SPEC_000280', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< string >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<string>", "G PRI_str.TAL.ARR1.SPEC.V0 input=std::vector< string >");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<string>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.ARR1.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< string >");
    assert.strictEqual(mapped, "Array<string>", "I map==expect PRI_str.TAL.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_NULLU_NORM_000281
   * @tc.name testInteg_PRI_str_TAL_NULLU_NORM_000281
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.NULLU.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.NULLU.NORM.V0
   */
  it('testInteg_PRI_str_TAL_NULLU_NORM_000281', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.NULLU.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.NULLU.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_NULLU_BOUND_000282
   * @tc.name testInteg_PRI_str_TAL_NULLU_BOUND_000282
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.NULLU.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.NULLU.BOUND.V0
   */
  it('testInteg_PRI_str_TAL_NULLU_BOUND_000282', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.NULLU.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.NULLU.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_NULLU_ERR_000283
   * @tc.name testInteg_PRI_str_TAL_NULLU_ERR_000283
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.TAL.NULLU.ERR.V0
   */
  it('testInteg_PRI_str_TAL_NULLU_ERR_000283', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.TAL.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.TAL.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_NULLU_SPEC_000284
   * @tc.name testInteg_PRI_str_TAL_NULLU_SPEC_000284
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.NULLU.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.NULLU.SPEC.V0
   */
  it('testInteg_PRI_str_TAL_NULLU_SPEC_000284', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.NULLU.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.NULLU.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_PROM_NORM_000285
   * @tc.name testInteg_PRI_str_TAL_PROM_NORM_000285
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.PROM.NORM.V0
   */
  it('testInteg_PRI_str_TAL_PROM_NORM_000285', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.PROM.NORM.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.PROM.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_PROM_BOUND_000286
   * @tc.name testInteg_PRI_str_TAL_PROM_BOUND_000286
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.PROM.BOUND.V0
   */
  it('testInteg_PRI_str_TAL_PROM_BOUND_000286', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.PROM.BOUND.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.PROM.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_PROM_ERR_000287
   * @tc.name testInteg_PRI_str_TAL_PROM_ERR_000287
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_str.TAL.PROM.ERR.V0
   */
  it('testInteg_PRI_str_TAL_PROM_ERR_000287', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_891985903__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_str.TAL.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.TAL.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_str_TAL_PROM_SPEC_000288
   * @tc.name testInteg_PRI_str_TAL_PROM_SPEC_000288
   * @tc.desc Verify roundtrip parse+map for PRI_str.TAL.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_str.TAL.PROM.SPEC.V0
   */
  it('testInteg_PRI_str_TAL_PROM_SPEC_000288', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "string";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "string", "G PRI_str.TAL.PROM.SPEC.V0 input=string");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = string;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_TAL_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.TAL.PROM.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_str.TAL.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("string");
    assert.strictEqual(mapped, "string", "I map==expect PRI_str.TAL.PROM.SPEC.V0");
  });

});
