#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hello World Skill - Python File Generator
Author: Created by user
Created: 2026-01-20
Version: 1.0.0

This script generates a Python hello world file.
"""

import sys
import os

def generate_hello_world_python(output_file="hello_world.py"):
    """
    Generate a Python file that prints "Hello, World!"
    
    Args:
        output_file (str): Output file path (default: hello_world.py)
    """
    python_content = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hello World Python Script
Generated by Hello World Skill
"""

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
'''
    
    # Write the file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(python_content)
    
    # Make it executable on Unix systems
    if os.name != 'nt':  # Not Windows
        os.chmod(output_file, 0o755)
    
    print(f"✓ Generated Python file: {output_file}")
    print(f"✓ File size: {len(python_content)} bytes")
    return output_file

def main():
    """Main entry point"""
    print("╔══════════════════════════════════════════════════════════════╗")
    print("║  DEBUG: Hello World Skill v1.0.0                            ║")
    print("║  DEBUG: Author: Created by user                             ║")
    print("║  DEBUG: Generating Python hello world file                 ║")
    print("╚══════════════════════════════════════════════════════════════╝")
    print()
    
    # Get output file from command line argument or use default
    output_file = sys.argv[1] if len(sys.argv) > 1 else "hello_world.py"
    
    try:
        generate_hello_world_python(output_file)
        print(f"\n✓ Success! You can now run: python3 {output_file}")
    except Exception as e:
        print(f"✗ Error generating file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
