/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_str_as_field', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RAW_NORM_000197
   * @tc.name testParse_PRI_str_FLD_RAW_NORM_000197
   * @tc.desc Verify parse declaration for PRI_str.FLD.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RAW.NORM.V0
   */
  it('testParse_PRI_str_FLD_RAW_NORM_000197', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RAW.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RAW.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RAW.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RAW.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RAW_BOUND_000198
   * @tc.name testParse_PRI_str_FLD_RAW_BOUND_000198
   * @tc.desc Verify parse declaration for PRI_str.FLD.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RAW.BOUND.V0
   */
  it('testParse_PRI_str_FLD_RAW_BOUND_000198', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RAW.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RAW.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RAW.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RAW.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RAW_ERR_000199
   * @tc.name testParse_PRI_str_FLD_RAW_ERR_000199
   * @tc.desc Verify parse declaration for PRI_str.FLD.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.RAW.ERR.V0
   */
  it('testParse_PRI_str_FLD_RAW_ERR_000199', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RAW_SPEC_000200
   * @tc.name testParse_PRI_str_FLD_RAW_SPEC_000200
   * @tc.desc Verify parse declaration for PRI_str.FLD.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RAW.SPEC.V0
   */
  it('testParse_PRI_str_FLD_RAW_SPEC_000200', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RAW.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RAW.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RAW.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RAW.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_OPT_NORM_000201
   * @tc.name testParse_PRI_str_FLD_OPT_NORM_000201
   * @tc.desc Verify parse declaration for PRI_str.FLD.OPT.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.OPT.NORM.V0
   */
  it('testParse_PRI_str_FLD_OPT_NORM_000201', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_OPT_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.OPT.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.OPT.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.OPT.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.OPT.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_OPT_BOUND_000202
   * @tc.name testParse_PRI_str_FLD_OPT_BOUND_000202
   * @tc.desc Verify parse declaration for PRI_str.FLD.OPT.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.OPT.BOUND.V0
   */
  it('testParse_PRI_str_FLD_OPT_BOUND_000202', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_OPT_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.OPT.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.OPT.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.OPT.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.OPT.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_OPT_ERR_000203
   * @tc.name testParse_PRI_str_FLD_OPT_ERR_000203
   * @tc.desc Verify parse declaration for PRI_str.FLD.OPT.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.OPT.ERR.V0
   */
  it('testParse_PRI_str_FLD_OPT_ERR_000203', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_OPT_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.OPT.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_OPT_SPEC_000204
   * @tc.name testParse_PRI_str_FLD_OPT_SPEC_000204
   * @tc.desc Verify parse declaration for PRI_str.FLD.OPT.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.OPT.SPEC.V0
   */
  it('testParse_PRI_str_FLD_OPT_SPEC_000204', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_OPT_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.OPT.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.OPT.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.OPT.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.OPT.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RO_NORM_000205
   * @tc.name testParse_PRI_str_FLD_RO_NORM_000205
   * @tc.desc Verify parse declaration for PRI_str.FLD.RO.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RO.NORM.V0
   */
  it('testParse_PRI_str_FLD_RO_NORM_000205', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RO_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RO.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RO.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RO.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RO.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RO_BOUND_000206
   * @tc.name testParse_PRI_str_FLD_RO_BOUND_000206
   * @tc.desc Verify parse declaration for PRI_str.FLD.RO.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RO.BOUND.V0
   */
  it('testParse_PRI_str_FLD_RO_BOUND_000206', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RO_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RO.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RO.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RO.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RO.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RO_ERR_000207
   * @tc.name testParse_PRI_str_FLD_RO_ERR_000207
   * @tc.desc Verify parse declaration for PRI_str.FLD.RO.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.RO.ERR.V0
   */
  it('testParse_PRI_str_FLD_RO_ERR_000207', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RO_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.RO.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_RO_SPEC_000208
   * @tc.name testParse_PRI_str_FLD_RO_SPEC_000208
   * @tc.desc Verify parse declaration for PRI_str.FLD.RO.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.RO.SPEC.V0
   */
  it('testParse_PRI_str_FLD_RO_SPEC_000208', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_RO_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.RO.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.RO.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.RO.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.RO.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PTR_NORM_000209
   * @tc.name testParse_PRI_str_FLD_PTR_NORM_000209
   * @tc.desc Verify parse declaration for PRI_str.FLD.PTR.NORM.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PTR.NORM.V0
   */
  it('testParse_PRI_str_FLD_PTR_NORM_000209', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PTR.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PTR.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PTR.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PTR.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PTR_BOUND_000210
   * @tc.name testParse_PRI_str_FLD_PTR_BOUND_000210
   * @tc.desc Verify parse declaration for PRI_str.FLD.PTR.BOUND.V0 input="string *" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PTR.BOUND.V0
   */
  it('testParse_PRI_str_FLD_PTR_BOUND_000210', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PTR.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PTR.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PTR.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PTR.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PTR_ERR_000211
   * @tc.name testParse_PRI_str_FLD_PTR_ERR_000211
   * @tc.desc Verify parse declaration for PRI_str.FLD.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.PTR.ERR.V0
   */
  it('testParse_PRI_str_FLD_PTR_ERR_000211', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PTR_SPEC_000212
   * @tc.name testParse_PRI_str_FLD_PTR_SPEC_000212
   * @tc.desc Verify parse declaration for PRI_str.FLD.PTR.SPEC.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PTR.SPEC.V0
   */
  it('testParse_PRI_str_FLD_PTR_SPEC_000212', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PTR.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PTR.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PTR.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PTR.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_ARR1_NORM_000213
   * @tc.name testParse_PRI_str_FLD_ARR1_NORM_000213
   * @tc.desc Verify parse declaration for PRI_str.FLD.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.ARR1.NORM.V0
   */
  it('testParse_PRI_str_FLD_ARR1_NORM_000213', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<string>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.ARR1.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.ARR1.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.ARR1.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<string>" || t.includes("Array"), "P FLD PRI_str.FLD.ARR1.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_ARR1_BOUND_000214
   * @tc.name testParse_PRI_str_FLD_ARR1_BOUND_000214
   * @tc.desc Verify parse declaration for PRI_str.FLD.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.ARR1.BOUND.V0
   */
  it('testParse_PRI_str_FLD_ARR1_BOUND_000214', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<string>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.ARR1.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.ARR1.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.ARR1.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<string>" || t.includes("Array"), "P FLD PRI_str.FLD.ARR1.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_ARR1_ERR_000215
   * @tc.name testParse_PRI_str_FLD_ARR1_ERR_000215
   * @tc.desc Verify parse declaration for PRI_str.FLD.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.ARR1.ERR.V0
   */
  it('testParse_PRI_str_FLD_ARR1_ERR_000215', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_ARR1_SPEC_000216
   * @tc.name testParse_PRI_str_FLD_ARR1_SPEC_000216
   * @tc.desc Verify parse declaration for PRI_str.FLD.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.ARR1.SPEC.V0
   */
  it('testParse_PRI_str_FLD_ARR1_SPEC_000216', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<string>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.ARR1.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.ARR1.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.ARR1.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<string>" || t.includes("Array"), "P FLD PRI_str.FLD.ARR1.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_NULLU_NORM_000217
   * @tc.name testParse_PRI_str_FLD_NULLU_NORM_000217
   * @tc.desc Verify parse declaration for PRI_str.FLD.NULLU.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.NULLU.NORM.V0
   */
  it('testParse_PRI_str_FLD_NULLU_NORM_000217', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.NULLU.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.NULLU.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.NULLU.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.NULLU.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_NULLU_BOUND_000218
   * @tc.name testParse_PRI_str_FLD_NULLU_BOUND_000218
   * @tc.desc Verify parse declaration for PRI_str.FLD.NULLU.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.NULLU.BOUND.V0
   */
  it('testParse_PRI_str_FLD_NULLU_BOUND_000218', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.NULLU.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.NULLU.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.NULLU.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.NULLU.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_NULLU_ERR_000219
   * @tc.name testParse_PRI_str_FLD_NULLU_ERR_000219
   * @tc.desc Verify parse declaration for PRI_str.FLD.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.NULLU.ERR.V0
   */
  it('testParse_PRI_str_FLD_NULLU_ERR_000219', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_NULLU_SPEC_000220
   * @tc.name testParse_PRI_str_FLD_NULLU_SPEC_000220
   * @tc.desc Verify parse declaration for PRI_str.FLD.NULLU.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.NULLU.SPEC.V0
   */
  it('testParse_PRI_str_FLD_NULLU_SPEC_000220', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.NULLU.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.NULLU.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.NULLU.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.NULLU.SPEC.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PROM_NORM_000221
   * @tc.name testParse_PRI_str_FLD_PROM_NORM_000221
   * @tc.desc Verify parse declaration for PRI_str.FLD.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PROM.NORM.V0
   */
  it('testParse_PRI_str_FLD_PROM_NORM_000221', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PROM.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PROM.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PROM.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PROM.NORM.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PROM_BOUND_000222
   * @tc.name testParse_PRI_str_FLD_PROM_BOUND_000222
   * @tc.desc Verify parse declaration for PRI_str.FLD.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PROM.BOUND.V0
   */
  it('testParse_PRI_str_FLD_PROM_BOUND_000222', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PROM.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PROM.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PROM.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PROM.BOUND.V0" + ' got=' + t);
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PROM_ERR_000223
   * @tc.name testParse_PRI_str_FLD_PROM_ERR_000223
   * @tc.desc Verify parse declaration for PRI_str.FLD.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.FLD.PROM.ERR.V0
   */
  it('testParse_PRI_str_FLD_PROM_ERR_000223', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.FLD.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_FLD_PROM_SPEC_000224
   * @tc.name testParse_PRI_str_FLD_PROM_SPEC_000224
   * @tc.desc Verify parse declaration for PRI_str.FLD.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.FLD.PROM.SPEC.V0
   */
  it('testParse_PRI_str_FLD_PROM_SPEC_000224', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: string; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_FLD_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.FLD.PROM.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_str.FLD.PROM.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_str.FLD.PROM.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "string" || t.includes("string"), "P FLD PRI_str.FLD.PROM.SPEC.V0" + ' got=' + t);
  });

});
