/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_str_as_generic', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_RAW_NORM_000289
   * @tc.name testParse_PRI_str_GEN_RAW_NORM_000289
   * @tc.desc Verify parse declaration for PRI_str.GEN.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.RAW.NORM.V0
   */
  it('testParse_PRI_str_GEN_RAW_NORM_000289', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_RAW_BOUND_000290
   * @tc.name testParse_PRI_str_GEN_RAW_BOUND_000290
   * @tc.desc Verify parse declaration for PRI_str.GEN.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.RAW.BOUND.V0
   */
  it('testParse_PRI_str_GEN_RAW_BOUND_000290', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_RAW_ERR_000291
   * @tc.name testParse_PRI_str_GEN_RAW_ERR_000291
   * @tc.desc Verify parse declaration for PRI_str.GEN.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.GEN.RAW.ERR.V0
   */
  it('testParse_PRI_str_GEN_RAW_ERR_000291', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.GEN.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_RAW_SPEC_000292
   * @tc.name testParse_PRI_str_GEN_RAW_SPEC_000292
   * @tc.desc Verify parse declaration for PRI_str.GEN.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.RAW.SPEC.V0
   */
  it('testParse_PRI_str_GEN_RAW_SPEC_000292', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_ARR1_NORM_000293
   * @tc.name testParse_PRI_str_GEN_ARR1_NORM_000293
   * @tc.desc Verify parse declaration for PRI_str.GEN.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.ARR1.NORM.V0
   */
  it('testParse_PRI_str_GEN_ARR1_NORM_000293', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<string>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_ARR1_BOUND_000294
   * @tc.name testParse_PRI_str_GEN_ARR1_BOUND_000294
   * @tc.desc Verify parse declaration for PRI_str.GEN.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.ARR1.BOUND.V0
   */
  it('testParse_PRI_str_GEN_ARR1_BOUND_000294', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<string>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_ARR1_ERR_000295
   * @tc.name testParse_PRI_str_GEN_ARR1_ERR_000295
   * @tc.desc Verify parse declaration for PRI_str.GEN.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.GEN.ARR1.ERR.V0
   */
  it('testParse_PRI_str_GEN_ARR1_ERR_000295', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.GEN.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_ARR1_SPEC_000296
   * @tc.name testParse_PRI_str_GEN_ARR1_SPEC_000296
   * @tc.desc Verify parse declaration for PRI_str.GEN.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.ARR1.SPEC.V0
   */
  it('testParse_PRI_str_GEN_ARR1_SPEC_000296', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<string>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_PROM_NORM_000297
   * @tc.name testParse_PRI_str_GEN_PROM_NORM_000297
   * @tc.desc Verify parse declaration for PRI_str.GEN.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.PROM.NORM.V0
   */
  it('testParse_PRI_str_GEN_PROM_NORM_000297', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_PROM_BOUND_000298
   * @tc.name testParse_PRI_str_GEN_PROM_BOUND_000298
   * @tc.desc Verify parse declaration for PRI_str.GEN.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.PROM.BOUND.V0
   */
  it('testParse_PRI_str_GEN_PROM_BOUND_000298', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_PROM_ERR_000299
   * @tc.name testParse_PRI_str_GEN_PROM_ERR_000299
   * @tc.desc Verify parse declaration for PRI_str.GEN.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.GEN.PROM.ERR.V0
   */
  it('testParse_PRI_str_GEN_PROM_ERR_000299', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.GEN.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_GEN_PROM_SPEC_000300
   * @tc.name testParse_PRI_str_GEN_PROM_SPEC_000300
   * @tc.desc Verify parse declaration for PRI_str.GEN.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.GEN.PROM.SPEC.V0
   */
  it('testParse_PRI_str_GEN_PROM_SPEC_000300', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends string>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_GEN_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.GEN.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.GEN.PROM.SPEC.V0");
  });

});
