/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_str_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_RAW_NORM_000253
   * @tc.name testParse_PRI_str_RET_RAW_NORM_000253
   * @tc.desc Verify parse declaration for PRI_str.RET.RAW.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.RAW.NORM.V0
   */
  it('testParse_PRI_str_RET_RAW_NORM_000253', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_RAW_BOUND_000254
   * @tc.name testParse_PRI_str_RET_RAW_BOUND_000254
   * @tc.desc Verify parse declaration for PRI_str.RET.RAW.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.RAW.BOUND.V0
   */
  it('testParse_PRI_str_RET_RAW_BOUND_000254', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_RAW_ERR_000255
   * @tc.name testParse_PRI_str_RET_RAW_ERR_000255
   * @tc.desc Verify parse declaration for PRI_str.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.RET.RAW.ERR.V0
   */
  it('testParse_PRI_str_RET_RAW_ERR_000255', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_RAW_SPEC_000256
   * @tc.name testParse_PRI_str_RET_RAW_SPEC_000256
   * @tc.desc Verify parse declaration for PRI_str.RET.RAW.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.RAW.SPEC.V0
   */
  it('testParse_PRI_str_RET_RAW_SPEC_000256', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PTR_NORM_000257
   * @tc.name testParse_PRI_str_RET_PTR_NORM_000257
   * @tc.desc Verify parse declaration for PRI_str.RET.PTR.NORM.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PTR.NORM.V0
   */
  it('testParse_PRI_str_RET_PTR_NORM_000257', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PTR_BOUND_000258
   * @tc.name testParse_PRI_str_RET_PTR_BOUND_000258
   * @tc.desc Verify parse declaration for PRI_str.RET.PTR.BOUND.V0 input="string *" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PTR.BOUND.V0
   */
  it('testParse_PRI_str_RET_PTR_BOUND_000258', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PTR_ERR_000259
   * @tc.name testParse_PRI_str_RET_PTR_ERR_000259
   * @tc.desc Verify parse declaration for PRI_str.RET.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.RET.PTR.ERR.V0
   */
  it('testParse_PRI_str_RET_PTR_ERR_000259', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PTR_SPEC_000260
   * @tc.name testParse_PRI_str_RET_PTR_SPEC_000260
   * @tc.desc Verify parse declaration for PRI_str.RET.PTR.SPEC.V0 input="string*" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PTR.SPEC.V0
   */
  it('testParse_PRI_str_RET_PTR_SPEC_000260', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_ARR1_NORM_000261
   * @tc.name testParse_PRI_str_RET_ARR1_NORM_000261
   * @tc.desc Verify parse declaration for PRI_str.RET.ARR1.NORM.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.ARR1.NORM.V0
   */
  it('testParse_PRI_str_RET_ARR1_NORM_000261', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_ARR1_BOUND_000262
   * @tc.name testParse_PRI_str_RET_ARR1_BOUND_000262
   * @tc.desc Verify parse declaration for PRI_str.RET.ARR1.BOUND.V0 input="std::vector<string>" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.ARR1.BOUND.V0
   */
  it('testParse_PRI_str_RET_ARR1_BOUND_000262', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_ARR1_ERR_000263
   * @tc.name testParse_PRI_str_RET_ARR1_ERR_000263
   * @tc.desc Verify parse declaration for PRI_str.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_252672969__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.RET.ARR1.ERR.V0
   */
  it('testParse_PRI_str_RET_ARR1_ERR_000263', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_ARR1_SPEC_000264
   * @tc.name testParse_PRI_str_RET_ARR1_SPEC_000264
   * @tc.desc Verify parse declaration for PRI_str.RET.ARR1.SPEC.V0 input="std::vector< string >" expect="Array<string>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.ARR1.SPEC.V0
   */
  it('testParse_PRI_str_RET_ARR1_SPEC_000264', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<string> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_NULLU_NORM_000265
   * @tc.name testParse_PRI_str_RET_NULLU_NORM_000265
   * @tc.desc Verify parse declaration for PRI_str.RET.NULLU.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.NULLU.NORM.V0
   */
  it('testParse_PRI_str_RET_NULLU_NORM_000265', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_NULLU_BOUND_000266
   * @tc.name testParse_PRI_str_RET_NULLU_BOUND_000266
   * @tc.desc Verify parse declaration for PRI_str.RET.NULLU.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.NULLU.BOUND.V0
   */
  it('testParse_PRI_str_RET_NULLU_BOUND_000266', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_NULLU_ERR_000267
   * @tc.name testParse_PRI_str_RET_NULLU_ERR_000267
   * @tc.desc Verify parse declaration for PRI_str.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.RET.NULLU.ERR.V0
   */
  it('testParse_PRI_str_RET_NULLU_ERR_000267', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_NULLU_SPEC_000268
   * @tc.name testParse_PRI_str_RET_NULLU_SPEC_000268
   * @tc.desc Verify parse declaration for PRI_str.RET.NULLU.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.NULLU.SPEC.V0
   */
  it('testParse_PRI_str_RET_NULLU_SPEC_000268', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PROM_NORM_000269
   * @tc.name testParse_PRI_str_RET_PROM_NORM_000269
   * @tc.desc Verify parse declaration for PRI_str.RET.PROM.NORM.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PROM.NORM.V0
   */
  it('testParse_PRI_str_RET_PROM_NORM_000269', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PROM_BOUND_000270
   * @tc.name testParse_PRI_str_RET_PROM_BOUND_000270
   * @tc.desc Verify parse declaration for PRI_str.RET.PROM.BOUND.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PROM.BOUND.V0
   */
  it('testParse_PRI_str_RET_PROM_BOUND_000270', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PROM_ERR_000271
   * @tc.name testParse_PRI_str_RET_PROM_ERR_000271
   * @tc.desc Verify parse declaration for PRI_str.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_891985903__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_str.RET.PROM.ERR.V0
   */
  it('testParse_PRI_str_RET_PROM_ERR_000271', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_str.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_str_RET_PROM_SPEC_000272
   * @tc.name testParse_PRI_str_RET_PROM_SPEC_000272
   * @tc.desc Verify parse declaration for PRI_str.RET.PROM.SPEC.V0 input="string" expect="string"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_str.RET.PROM.SPEC.V0
   */
  it('testParse_PRI_str_RET_PROM_SPEC_000272', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): string { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_str_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_str.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_str.RET.PROM.SPEC.V0");
  });

});
