/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_bool_as_generic', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_RAW_NORM_000185
   * @tc.name testParse_PRI_bool_GEN_RAW_NORM_000185
   * @tc.desc Verify parse declaration for PRI_bool.GEN.RAW.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.RAW.NORM.V0
   */
  it('testParse_PRI_bool_GEN_RAW_NORM_000185', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_RAW_BOUND_000186
   * @tc.name testParse_PRI_bool_GEN_RAW_BOUND_000186
   * @tc.desc Verify parse declaration for PRI_bool.GEN.RAW.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.RAW.BOUND.V0
   */
  it('testParse_PRI_bool_GEN_RAW_BOUND_000186', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_RAW_ERR_000187
   * @tc.name testParse_PRI_bool_GEN_RAW_ERR_000187
   * @tc.desc Verify parse declaration for PRI_bool.GEN.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.GEN.RAW.ERR.V0
   */
  it('testParse_PRI_bool_GEN_RAW_ERR_000187', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.GEN.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_RAW_SPEC_000188
   * @tc.name testParse_PRI_bool_GEN_RAW_SPEC_000188
   * @tc.desc Verify parse declaration for PRI_bool.GEN.RAW.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.RAW.SPEC.V0
   */
  it('testParse_PRI_bool_GEN_RAW_SPEC_000188', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_ARR1_NORM_000189
   * @tc.name testParse_PRI_bool_GEN_ARR1_NORM_000189
   * @tc.desc Verify parse declaration for PRI_bool.GEN.ARR1.NORM.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.ARR1.NORM.V0
   */
  it('testParse_PRI_bool_GEN_ARR1_NORM_000189', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<boolean>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_ARR1_BOUND_000190
   * @tc.name testParse_PRI_bool_GEN_ARR1_BOUND_000190
   * @tc.desc Verify parse declaration for PRI_bool.GEN.ARR1.BOUND.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.ARR1.BOUND.V0
   */
  it('testParse_PRI_bool_GEN_ARR1_BOUND_000190', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<boolean>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_ARR1_ERR_000191
   * @tc.name testParse_PRI_bool_GEN_ARR1_ERR_000191
   * @tc.desc Verify parse declaration for PRI_bool.GEN.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1196001538__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.GEN.ARR1.ERR.V0
   */
  it('testParse_PRI_bool_GEN_ARR1_ERR_000191', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.GEN.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_ARR1_SPEC_000192
   * @tc.name testParse_PRI_bool_GEN_ARR1_SPEC_000192
   * @tc.desc Verify parse declaration for PRI_bool.GEN.ARR1.SPEC.V0 input="std::vector< bool >" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.ARR1.SPEC.V0
   */
  it('testParse_PRI_bool_GEN_ARR1_SPEC_000192', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<boolean>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_PROM_NORM_000193
   * @tc.name testParse_PRI_bool_GEN_PROM_NORM_000193
   * @tc.desc Verify parse declaration for PRI_bool.GEN.PROM.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.PROM.NORM.V0
   */
  it('testParse_PRI_bool_GEN_PROM_NORM_000193', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_PROM_BOUND_000194
   * @tc.name testParse_PRI_bool_GEN_PROM_BOUND_000194
   * @tc.desc Verify parse declaration for PRI_bool.GEN.PROM.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.PROM.BOUND.V0
   */
  it('testParse_PRI_bool_GEN_PROM_BOUND_000194', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_PROM_ERR_000195
   * @tc.name testParse_PRI_bool_GEN_PROM_ERR_000195
   * @tc.desc Verify parse declaration for PRI_bool.GEN.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.GEN.PROM.ERR.V0
   */
  it('testParse_PRI_bool_GEN_PROM_ERR_000195', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.GEN.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_GEN_PROM_SPEC_000196
   * @tc.name testParse_PRI_bool_GEN_PROM_SPEC_000196
   * @tc.desc Verify parse declaration for PRI_bool.GEN.PROM.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.GEN.PROM.SPEC.V0
   */
  it('testParse_PRI_bool_GEN_PROM_SPEC_000196', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends boolean>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_GEN_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.GEN.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.GEN.PROM.SPEC.V0");
  });

});
