/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_bool_as_param', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RAW_NORM_000121
   * @tc.name testParse_PRI_bool_PAR_RAW_NORM_000121
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RAW.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RAW.NORM.V0
   */
  it('testParse_PRI_bool_PAR_RAW_NORM_000121', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RAW_BOUND_000122
   * @tc.name testParse_PRI_bool_PAR_RAW_BOUND_000122
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RAW.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RAW.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_RAW_BOUND_000122', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RAW_ERR_000123
   * @tc.name testParse_PRI_bool_PAR_RAW_ERR_000123
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.RAW.ERR.V0
   */
  it('testParse_PRI_bool_PAR_RAW_ERR_000123', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RAW_SPEC_000124
   * @tc.name testParse_PRI_bool_PAR_RAW_SPEC_000124
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RAW.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RAW.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_RAW_SPEC_000124', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_OPT_NORM_000125
   * @tc.name testParse_PRI_bool_PAR_OPT_NORM_000125
   * @tc.desc Verify parse declaration for PRI_bool.PAR.OPT.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.OPT.NORM.V0
   */
  it('testParse_PRI_bool_PAR_OPT_NORM_000125', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_OPT_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.OPT.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.OPT.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_OPT_BOUND_000126
   * @tc.name testParse_PRI_bool_PAR_OPT_BOUND_000126
   * @tc.desc Verify parse declaration for PRI_bool.PAR.OPT.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.OPT.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_OPT_BOUND_000126', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_OPT_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.OPT.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.OPT.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_OPT_ERR_000127
   * @tc.name testParse_PRI_bool_PAR_OPT_ERR_000127
   * @tc.desc Verify parse declaration for PRI_bool.PAR.OPT.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.OPT.ERR.V0
   */
  it('testParse_PRI_bool_PAR_OPT_ERR_000127', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_OPT_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.OPT.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_OPT_SPEC_000128
   * @tc.name testParse_PRI_bool_PAR_OPT_SPEC_000128
   * @tc.desc Verify parse declaration for PRI_bool.PAR.OPT.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.OPT.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_OPT_SPEC_000128', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_OPT_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.OPT.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.OPT.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RO_NORM_000129
   * @tc.name testParse_PRI_bool_PAR_RO_NORM_000129
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RO.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RO.NORM.V0
   */
  it('testParse_PRI_bool_PAR_RO_NORM_000129', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RO_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RO.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RO.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RO_BOUND_000130
   * @tc.name testParse_PRI_bool_PAR_RO_BOUND_000130
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RO.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RO.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_RO_BOUND_000130', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RO_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RO.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RO.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RO_ERR_000131
   * @tc.name testParse_PRI_bool_PAR_RO_ERR_000131
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RO.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.RO.ERR.V0
   */
  it('testParse_PRI_bool_PAR_RO_ERR_000131', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RO_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.RO.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_RO_SPEC_000132
   * @tc.name testParse_PRI_bool_PAR_RO_SPEC_000132
   * @tc.desc Verify parse declaration for PRI_bool.PAR.RO.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.RO.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_RO_SPEC_000132', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_RO_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.RO.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.RO.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PTR_NORM_000133
   * @tc.name testParse_PRI_bool_PAR_PTR_NORM_000133
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PTR.NORM.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PTR.NORM.V0
   */
  it('testParse_PRI_bool_PAR_PTR_NORM_000133', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PTR_BOUND_000134
   * @tc.name testParse_PRI_bool_PAR_PTR_BOUND_000134
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PTR.BOUND.V0 input="bool *" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PTR.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_PTR_BOUND_000134', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PTR_ERR_000135
   * @tc.name testParse_PRI_bool_PAR_PTR_ERR_000135
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.PTR.ERR.V0
   */
  it('testParse_PRI_bool_PAR_PTR_ERR_000135', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PTR_SPEC_000136
   * @tc.name testParse_PRI_bool_PAR_PTR_SPEC_000136
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PTR.SPEC.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PTR.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_PTR_SPEC_000136', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_ARR1_NORM_000137
   * @tc.name testParse_PRI_bool_PAR_ARR1_NORM_000137
   * @tc.desc Verify parse declaration for PRI_bool.PAR.ARR1.NORM.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.ARR1.NORM.V0
   */
  it('testParse_PRI_bool_PAR_ARR1_NORM_000137', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<boolean>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_ARR1_BOUND_000138
   * @tc.name testParse_PRI_bool_PAR_ARR1_BOUND_000138
   * @tc.desc Verify parse declaration for PRI_bool.PAR.ARR1.BOUND.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.ARR1.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_ARR1_BOUND_000138', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<boolean>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_ARR1_ERR_000139
   * @tc.name testParse_PRI_bool_PAR_ARR1_ERR_000139
   * @tc.desc Verify parse declaration for PRI_bool.PAR.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1196001538__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.ARR1.ERR.V0
   */
  it('testParse_PRI_bool_PAR_ARR1_ERR_000139', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_ARR1_SPEC_000140
   * @tc.name testParse_PRI_bool_PAR_ARR1_SPEC_000140
   * @tc.desc Verify parse declaration for PRI_bool.PAR.ARR1.SPEC.V0 input="std::vector< bool >" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.ARR1.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_ARR1_SPEC_000140', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<boolean>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_NULLU_NORM_000141
   * @tc.name testParse_PRI_bool_PAR_NULLU_NORM_000141
   * @tc.desc Verify parse declaration for PRI_bool.PAR.NULLU.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.NULLU.NORM.V0
   */
  it('testParse_PRI_bool_PAR_NULLU_NORM_000141', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_NULLU_BOUND_000142
   * @tc.name testParse_PRI_bool_PAR_NULLU_BOUND_000142
   * @tc.desc Verify parse declaration for PRI_bool.PAR.NULLU.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.NULLU.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_NULLU_BOUND_000142', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_NULLU_ERR_000143
   * @tc.name testParse_PRI_bool_PAR_NULLU_ERR_000143
   * @tc.desc Verify parse declaration for PRI_bool.PAR.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.NULLU.ERR.V0
   */
  it('testParse_PRI_bool_PAR_NULLU_ERR_000143', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_NULLU_SPEC_000144
   * @tc.name testParse_PRI_bool_PAR_NULLU_SPEC_000144
   * @tc.desc Verify parse declaration for PRI_bool.PAR.NULLU.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.NULLU.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_NULLU_SPEC_000144', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PROM_NORM_000145
   * @tc.name testParse_PRI_bool_PAR_PROM_NORM_000145
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PROM.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PROM.NORM.V0
   */
  it('testParse_PRI_bool_PAR_PROM_NORM_000145', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PROM_BOUND_000146
   * @tc.name testParse_PRI_bool_PAR_PROM_BOUND_000146
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PROM.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PROM.BOUND.V0
   */
  it('testParse_PRI_bool_PAR_PROM_BOUND_000146', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PROM_ERR_000147
   * @tc.name testParse_PRI_bool_PAR_PROM_ERR_000147
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.PAR.PROM.ERR.V0
   */
  it('testParse_PRI_bool_PAR_PROM_ERR_000147', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.PAR.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_PAR_PROM_SPEC_000148
   * @tc.name testParse_PRI_bool_PAR_PROM_SPEC_000148
   * @tc.desc Verify parse declaration for PRI_bool.PAR.PROM.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.PAR.PROM.SPEC.V0
   */
  it('testParse_PRI_bool_PAR_PROM_SPEC_000148', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: boolean): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_PAR_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.PAR.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.PAR.PROM.SPEC.V0");
  });

});
