/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_bool_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_RAW_NORM_000149
   * @tc.name testParse_PRI_bool_RET_RAW_NORM_000149
   * @tc.desc Verify parse declaration for PRI_bool.RET.RAW.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.RAW.NORM.V0
   */
  it('testParse_PRI_bool_RET_RAW_NORM_000149', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_RAW_BOUND_000150
   * @tc.name testParse_PRI_bool_RET_RAW_BOUND_000150
   * @tc.desc Verify parse declaration for PRI_bool.RET.RAW.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.RAW.BOUND.V0
   */
  it('testParse_PRI_bool_RET_RAW_BOUND_000150', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_RAW_ERR_000151
   * @tc.name testParse_PRI_bool_RET_RAW_ERR_000151
   * @tc.desc Verify parse declaration for PRI_bool.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.RET.RAW.ERR.V0
   */
  it('testParse_PRI_bool_RET_RAW_ERR_000151', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_RAW_SPEC_000152
   * @tc.name testParse_PRI_bool_RET_RAW_SPEC_000152
   * @tc.desc Verify parse declaration for PRI_bool.RET.RAW.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.RAW.SPEC.V0
   */
  it('testParse_PRI_bool_RET_RAW_SPEC_000152', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PTR_NORM_000153
   * @tc.name testParse_PRI_bool_RET_PTR_NORM_000153
   * @tc.desc Verify parse declaration for PRI_bool.RET.PTR.NORM.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PTR.NORM.V0
   */
  it('testParse_PRI_bool_RET_PTR_NORM_000153', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PTR_BOUND_000154
   * @tc.name testParse_PRI_bool_RET_PTR_BOUND_000154
   * @tc.desc Verify parse declaration for PRI_bool.RET.PTR.BOUND.V0 input="bool *" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PTR.BOUND.V0
   */
  it('testParse_PRI_bool_RET_PTR_BOUND_000154', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PTR_ERR_000155
   * @tc.name testParse_PRI_bool_RET_PTR_ERR_000155
   * @tc.desc Verify parse declaration for PRI_bool.RET.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.RET.PTR.ERR.V0
   */
  it('testParse_PRI_bool_RET_PTR_ERR_000155', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PTR_SPEC_000156
   * @tc.name testParse_PRI_bool_RET_PTR_SPEC_000156
   * @tc.desc Verify parse declaration for PRI_bool.RET.PTR.SPEC.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PTR.SPEC.V0
   */
  it('testParse_PRI_bool_RET_PTR_SPEC_000156', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_ARR1_NORM_000157
   * @tc.name testParse_PRI_bool_RET_ARR1_NORM_000157
   * @tc.desc Verify parse declaration for PRI_bool.RET.ARR1.NORM.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.ARR1.NORM.V0
   */
  it('testParse_PRI_bool_RET_ARR1_NORM_000157', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_ARR1_BOUND_000158
   * @tc.name testParse_PRI_bool_RET_ARR1_BOUND_000158
   * @tc.desc Verify parse declaration for PRI_bool.RET.ARR1.BOUND.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.ARR1.BOUND.V0
   */
  it('testParse_PRI_bool_RET_ARR1_BOUND_000158', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_ARR1_ERR_000159
   * @tc.name testParse_PRI_bool_RET_ARR1_ERR_000159
   * @tc.desc Verify parse declaration for PRI_bool.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1196001538__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.RET.ARR1.ERR.V0
   */
  it('testParse_PRI_bool_RET_ARR1_ERR_000159', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_ARR1_SPEC_000160
   * @tc.name testParse_PRI_bool_RET_ARR1_SPEC_000160
   * @tc.desc Verify parse declaration for PRI_bool.RET.ARR1.SPEC.V0 input="std::vector< bool >" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.ARR1.SPEC.V0
   */
  it('testParse_PRI_bool_RET_ARR1_SPEC_000160', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_NULLU_NORM_000161
   * @tc.name testParse_PRI_bool_RET_NULLU_NORM_000161
   * @tc.desc Verify parse declaration for PRI_bool.RET.NULLU.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.NULLU.NORM.V0
   */
  it('testParse_PRI_bool_RET_NULLU_NORM_000161', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_NULLU_BOUND_000162
   * @tc.name testParse_PRI_bool_RET_NULLU_BOUND_000162
   * @tc.desc Verify parse declaration for PRI_bool.RET.NULLU.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.NULLU.BOUND.V0
   */
  it('testParse_PRI_bool_RET_NULLU_BOUND_000162', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_NULLU_ERR_000163
   * @tc.name testParse_PRI_bool_RET_NULLU_ERR_000163
   * @tc.desc Verify parse declaration for PRI_bool.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.RET.NULLU.ERR.V0
   */
  it('testParse_PRI_bool_RET_NULLU_ERR_000163', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_NULLU_SPEC_000164
   * @tc.name testParse_PRI_bool_RET_NULLU_SPEC_000164
   * @tc.desc Verify parse declaration for PRI_bool.RET.NULLU.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.NULLU.SPEC.V0
   */
  it('testParse_PRI_bool_RET_NULLU_SPEC_000164', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PROM_NORM_000165
   * @tc.name testParse_PRI_bool_RET_PROM_NORM_000165
   * @tc.desc Verify parse declaration for PRI_bool.RET.PROM.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PROM.NORM.V0
   */
  it('testParse_PRI_bool_RET_PROM_NORM_000165', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PROM_BOUND_000166
   * @tc.name testParse_PRI_bool_RET_PROM_BOUND_000166
   * @tc.desc Verify parse declaration for PRI_bool.RET.PROM.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PROM.BOUND.V0
   */
  it('testParse_PRI_bool_RET_PROM_BOUND_000166', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PROM_ERR_000167
   * @tc.name testParse_PRI_bool_RET_PROM_ERR_000167
   * @tc.desc Verify parse declaration for PRI_bool.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_bool.RET.PROM.ERR.V0
   */
  it('testParse_PRI_bool_RET_PROM_ERR_000167', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_bool_RET_PROM_SPEC_000168
   * @tc.name testParse_PRI_bool_RET_PROM_SPEC_000168
   * @tc.desc Verify parse declaration for PRI_bool.RET.PROM.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_bool.RET.PROM.SPEC.V0
   */
  it('testParse_PRI_bool_RET_PROM_SPEC_000168', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.SPEC.V0");
  });

});
