/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_void_as_param', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RAW_NORM_000025
   * @tc.name testInteg_PRI_void_PAR_RAW_NORM_000025
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RAW.NORM.V0
   */
  it('testInteg_PRI_void_PAR_RAW_NORM_000025', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RAW.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RAW_BOUND_000026
   * @tc.name testInteg_PRI_void_PAR_RAW_BOUND_000026
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RAW.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_RAW_BOUND_000026', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RAW.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RAW_ERR_000027
   * @tc.name testInteg_PRI_void_PAR_RAW_ERR_000027
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.RAW.ERR.V0
   */
  it('testInteg_PRI_void_PAR_RAW_ERR_000027', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RAW_SPEC_000028
   * @tc.name testInteg_PRI_void_PAR_RAW_SPEC_000028
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RAW.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_RAW_SPEC_000028', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RAW.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_OPT_NORM_000029
   * @tc.name testInteg_PRI_void_PAR_OPT_NORM_000029
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.OPT.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.OPT.NORM.V0
   */
  it('testInteg_PRI_void_PAR_OPT_NORM_000029', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.OPT.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_OPT_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.OPT.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.OPT.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.OPT.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_OPT_BOUND_000030
   * @tc.name testInteg_PRI_void_PAR_OPT_BOUND_000030
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.OPT.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.OPT.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_OPT_BOUND_000030', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.OPT.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_OPT_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.OPT.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.OPT.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.OPT.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_OPT_ERR_000031
   * @tc.name testInteg_PRI_void_PAR_OPT_ERR_000031
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.OPT.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.OPT.ERR.V0
   */
  it('testInteg_PRI_void_PAR_OPT_ERR_000031', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.OPT.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_OPT_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.OPT.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_OPT_SPEC_000032
   * @tc.name testInteg_PRI_void_PAR_OPT_SPEC_000032
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.OPT.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.OPT.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_OPT_SPEC_000032', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.OPT.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_OPT_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.OPT.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.OPT.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.OPT.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RO_NORM_000033
   * @tc.name testInteg_PRI_void_PAR_RO_NORM_000033
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RO.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RO.NORM.V0
   */
  it('testInteg_PRI_void_PAR_RO_NORM_000033', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RO.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RO_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RO.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RO.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RO.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RO_BOUND_000034
   * @tc.name testInteg_PRI_void_PAR_RO_BOUND_000034
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RO.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RO.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_RO_BOUND_000034', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RO.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RO_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RO.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RO.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RO.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RO_ERR_000035
   * @tc.name testInteg_PRI_void_PAR_RO_ERR_000035
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RO.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.RO.ERR.V0
   */
  it('testInteg_PRI_void_PAR_RO_ERR_000035', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.RO.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RO_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.RO.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_RO_SPEC_000036
   * @tc.name testInteg_PRI_void_PAR_RO_SPEC_000036
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.RO.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.RO.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_RO_SPEC_000036', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.RO.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_RO_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.RO.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.RO.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.RO.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_ARR1_NORM_000037
   * @tc.name testInteg_PRI_void_PAR_ARR1_NORM_000037
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.ARR1.NORM.V0
   */
  it('testInteg_PRI_void_PAR_ARR1_NORM_000037', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.PAR.ARR1.NORM.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<void>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.PAR.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_ARR1_BOUND_000038
   * @tc.name testInteg_PRI_void_PAR_ARR1_BOUND_000038
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.ARR1.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_ARR1_BOUND_000038', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.PAR.ARR1.BOUND.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<void>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.PAR.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_ARR1_ERR_000039
   * @tc.name testInteg_PRI_void_PAR_ARR1_ERR_000039
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.ARR1.ERR.V0
   */
  it('testInteg_PRI_void_PAR_ARR1_ERR_000039', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_1177537132__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_ARR1_SPEC_000040
   * @tc.name testInteg_PRI_void_PAR_ARR1_SPEC_000040
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.ARR1.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_ARR1_SPEC_000040', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< void >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.PAR.ARR1.SPEC.V0 input=std::vector< void >");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: Array<void>): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< void >");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.PAR.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_NULLU_NORM_000041
   * @tc.name testInteg_PRI_void_PAR_NULLU_NORM_000041
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.NULLU.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.NULLU.NORM.V0
   */
  it('testInteg_PRI_void_PAR_NULLU_NORM_000041', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.NULLU.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_NULLU_BOUND_000042
   * @tc.name testInteg_PRI_void_PAR_NULLU_BOUND_000042
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.NULLU.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.NULLU.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_NULLU_BOUND_000042', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.NULLU.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_NULLU_ERR_000043
   * @tc.name testInteg_PRI_void_PAR_NULLU_ERR_000043
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.NULLU.ERR.V0
   */
  it('testInteg_PRI_void_PAR_NULLU_ERR_000043', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_NULLU_SPEC_000044
   * @tc.name testInteg_PRI_void_PAR_NULLU_SPEC_000044
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.NULLU.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.NULLU.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_NULLU_SPEC_000044', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.NULLU.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_PROM_NORM_000045
   * @tc.name testInteg_PRI_void_PAR_PROM_NORM_000045
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.PROM.NORM.V0
   */
  it('testInteg_PRI_void_PAR_PROM_NORM_000045', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.PROM.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_PROM_BOUND_000046
   * @tc.name testInteg_PRI_void_PAR_PROM_BOUND_000046
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.PROM.BOUND.V0
   */
  it('testInteg_PRI_void_PAR_PROM_BOUND_000046', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.PROM.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_PROM_ERR_000047
   * @tc.name testInteg_PRI_void_PAR_PROM_ERR_000047
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.PAR.PROM.ERR.V0
   */
  it('testInteg_PRI_void_PAR_PROM_ERR_000047', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.PAR.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.PAR.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_PAR_PROM_SPEC_000048
   * @tc.name testInteg_PRI_void_PAR_PROM_SPEC_000048
   * @tc.desc Verify roundtrip parse+map for PRI_void.PAR.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.PAR.PROM.SPEC.V0
   */
  it('testInteg_PRI_void_PAR_PROM_SPEC_000048', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.PAR.PROM.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Fn(p: void): void {}\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_PAR_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.PAR.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.PAR.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.PAR.PROM.SPEC.V0");
  });

});
