/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_void_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_RAW_NORM_000049
   * @tc.name testInteg_PRI_void_RET_RAW_NORM_000049
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.RAW.NORM.V0
   */
  it('testInteg_PRI_void_RET_RAW_NORM_000049', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.RAW.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_RAW_BOUND_000050
   * @tc.name testInteg_PRI_void_RET_RAW_BOUND_000050
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.RAW.BOUND.V0
   */
  it('testInteg_PRI_void_RET_RAW_BOUND_000050', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.RAW.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_RAW_ERR_000051
   * @tc.name testInteg_PRI_void_RET_RAW_ERR_000051
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.RET.RAW.ERR.V0
   */
  it('testInteg_PRI_void_RET_RAW_ERR_000051', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.RET.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_RAW_SPEC_000052
   * @tc.name testInteg_PRI_void_RET_RAW_SPEC_000052
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.RAW.SPEC.V0
   */
  it('testInteg_PRI_void_RET_RAW_SPEC_000052', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.RAW.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_ARR1_NORM_000053
   * @tc.name testInteg_PRI_void_RET_ARR1_NORM_000053
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.ARR1.NORM.V0
   */
  it('testInteg_PRI_void_RET_ARR1_NORM_000053', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.RET.ARR1.NORM.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_ARR1_BOUND_000054
   * @tc.name testInteg_PRI_void_RET_ARR1_BOUND_000054
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.ARR1.BOUND.V0
   */
  it('testInteg_PRI_void_RET_ARR1_BOUND_000054', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.RET.ARR1.BOUND.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_ARR1_ERR_000055
   * @tc.name testInteg_PRI_void_RET_ARR1_ERR_000055
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.RET.ARR1.ERR.V0
   */
  it('testInteg_PRI_void_RET_ARR1_ERR_000055', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_1177537132__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.RET.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_ARR1_SPEC_000056
   * @tc.name testInteg_PRI_void_RET_ARR1_SPEC_000056
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.ARR1.SPEC.V0
   */
  it('testInteg_PRI_void_RET_ARR1_SPEC_000056', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< void >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.RET.ARR1.SPEC.V0 input=std::vector< void >");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< void >");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_NULLU_NORM_000057
   * @tc.name testInteg_PRI_void_RET_NULLU_NORM_000057
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.NULLU.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.NULLU.NORM.V0
   */
  it('testInteg_PRI_void_RET_NULLU_NORM_000057', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.NULLU.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_NULLU_BOUND_000058
   * @tc.name testInteg_PRI_void_RET_NULLU_BOUND_000058
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.NULLU.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.NULLU.BOUND.V0
   */
  it('testInteg_PRI_void_RET_NULLU_BOUND_000058', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.NULLU.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_NULLU_ERR_000059
   * @tc.name testInteg_PRI_void_RET_NULLU_ERR_000059
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.RET.NULLU.ERR.V0
   */
  it('testInteg_PRI_void_RET_NULLU_ERR_000059', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.RET.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_NULLU_SPEC_000060
   * @tc.name testInteg_PRI_void_RET_NULLU_SPEC_000060
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.NULLU.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.NULLU.SPEC.V0
   */
  it('testInteg_PRI_void_RET_NULLU_SPEC_000060', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.NULLU.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_PROM_NORM_000061
   * @tc.name testInteg_PRI_void_RET_PROM_NORM_000061
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.PROM.NORM.V0
   */
  it('testInteg_PRI_void_RET_PROM_NORM_000061', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.PROM.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_PROM_BOUND_000062
   * @tc.name testInteg_PRI_void_RET_PROM_BOUND_000062
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.PROM.BOUND.V0
   */
  it('testInteg_PRI_void_RET_PROM_BOUND_000062', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.PROM.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_PROM_ERR_000063
   * @tc.name testInteg_PRI_void_RET_PROM_ERR_000063
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.RET.PROM.ERR.V0
   */
  it('testInteg_PRI_void_RET_PROM_ERR_000063', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.RET.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_RET_PROM_SPEC_000064
   * @tc.name testInteg_PRI_void_RET_PROM_SPEC_000064
   * @tc.desc Verify roundtrip parse+map for PRI_void.RET.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.RET.PROM.SPEC.V0
   */
  it('testInteg_PRI_void_RET_PROM_SPEC_000064', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.RET.PROM.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.RET.PROM.SPEC.V0");
  });

});
