/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_void_as_typealias', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_RAW_NORM_000065
   * @tc.name testInteg_PRI_void_TAL_RAW_NORM_000065
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.RAW.NORM.V0
   */
  it('testInteg_PRI_void_TAL_RAW_NORM_000065', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.RAW.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_RAW_BOUND_000066
   * @tc.name testInteg_PRI_void_TAL_RAW_BOUND_000066
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.RAW.BOUND.V0
   */
  it('testInteg_PRI_void_TAL_RAW_BOUND_000066', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.RAW.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_RAW_ERR_000067
   * @tc.name testInteg_PRI_void_TAL_RAW_ERR_000067
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.TAL.RAW.ERR.V0
   */
  it('testInteg_PRI_void_TAL_RAW_ERR_000067', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.TAL.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_RAW_SPEC_000068
   * @tc.name testInteg_PRI_void_TAL_RAW_SPEC_000068
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.RAW.SPEC.V0
   */
  it('testInteg_PRI_void_TAL_RAW_SPEC_000068', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.RAW.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_ARR1_NORM_000069
   * @tc.name testInteg_PRI_void_TAL_ARR1_NORM_000069
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.ARR1.NORM.V0
   */
  it('testInteg_PRI_void_TAL_ARR1_NORM_000069', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.TAL.ARR1.NORM.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.TAL.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_ARR1_BOUND_000070
   * @tc.name testInteg_PRI_void_TAL_ARR1_BOUND_000070
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.ARR1.BOUND.V0
   */
  it('testInteg_PRI_void_TAL_ARR1_BOUND_000070', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<void>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.TAL.ARR1.BOUND.V0 input=std::vector<void>");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<void>");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.TAL.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_ARR1_ERR_000071
   * @tc.name testInteg_PRI_void_TAL_ARR1_ERR_000071
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.TAL.ARR1.ERR.V0
   */
  it('testInteg_PRI_void_TAL_ARR1_ERR_000071', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_1177537132__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.TAL.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_ARR1_SPEC_000072
   * @tc.name testInteg_PRI_void_TAL_ARR1_SPEC_000072
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.ARR1.SPEC.V0
   */
  it('testInteg_PRI_void_TAL_ARR1_SPEC_000072', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< void >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<void>", "G PRI_void.TAL.ARR1.SPEC.V0 input=std::vector< void >");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< void >");
    assert.strictEqual(mapped, "Array<void>", "I map==expect PRI_void.TAL.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_NULLU_NORM_000073
   * @tc.name testInteg_PRI_void_TAL_NULLU_NORM_000073
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.NULLU.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.NULLU.NORM.V0
   */
  it('testInteg_PRI_void_TAL_NULLU_NORM_000073', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.NULLU.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_NULLU_BOUND_000074
   * @tc.name testInteg_PRI_void_TAL_NULLU_BOUND_000074
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.NULLU.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.NULLU.BOUND.V0
   */
  it('testInteg_PRI_void_TAL_NULLU_BOUND_000074', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.NULLU.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_NULLU_ERR_000075
   * @tc.name testInteg_PRI_void_TAL_NULLU_ERR_000075
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.TAL.NULLU.ERR.V0
   */
  it('testInteg_PRI_void_TAL_NULLU_ERR_000075', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.TAL.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_NULLU_SPEC_000076
   * @tc.name testInteg_PRI_void_TAL_NULLU_SPEC_000076
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.NULLU.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.NULLU.SPEC.V0
   */
  it('testInteg_PRI_void_TAL_NULLU_SPEC_000076', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.NULLU.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_PROM_NORM_000077
   * @tc.name testInteg_PRI_void_TAL_PROM_NORM_000077
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.PROM.NORM.V0
   */
  it('testInteg_PRI_void_TAL_PROM_NORM_000077', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.PROM.NORM.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_PROM_BOUND_000078
   * @tc.name testInteg_PRI_void_TAL_PROM_BOUND_000078
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.PROM.BOUND.V0
   */
  it('testInteg_PRI_void_TAL_PROM_BOUND_000078', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.PROM.BOUND.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_PROM_ERR_000079
   * @tc.name testInteg_PRI_void_TAL_PROM_ERR_000079
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_void.TAL.PROM.ERR.V0
   */
  it('testInteg_PRI_void_TAL_PROM_ERR_000079', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3625364__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_void.TAL.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_void_TAL_PROM_SPEC_000080
   * @tc.name testInteg_PRI_void_TAL_PROM_SPEC_000080
   * @tc.desc Verify roundtrip parse+map for PRI_void.TAL.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_void.TAL.PROM.SPEC.V0
   */
  it('testInteg_PRI_void_TAL_PROM_SPEC_000080', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "void";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "void", "G PRI_void.TAL.PROM.SPEC.V0 input=void");
    // [P]
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("void");
    assert.strictEqual(mapped, "void", "I map==expect PRI_void.TAL.PROM.SPEC.V0");
  });

});
