/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_void_as_generic', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_RAW_NORM_000081
   * @tc.name testParse_PRI_void_GEN_RAW_NORM_000081
   * @tc.desc Verify parse declaration for PRI_void.GEN.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.RAW.NORM.V0
   */
  it('testParse_PRI_void_GEN_RAW_NORM_000081', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_RAW_BOUND_000082
   * @tc.name testParse_PRI_void_GEN_RAW_BOUND_000082
   * @tc.desc Verify parse declaration for PRI_void.GEN.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.RAW.BOUND.V0
   */
  it('testParse_PRI_void_GEN_RAW_BOUND_000082', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_RAW_ERR_000083
   * @tc.name testParse_PRI_void_GEN_RAW_ERR_000083
   * @tc.desc Verify parse declaration for PRI_void.GEN.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.GEN.RAW.ERR.V0
   */
  it('testParse_PRI_void_GEN_RAW_ERR_000083', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.GEN.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_RAW_SPEC_000084
   * @tc.name testParse_PRI_void_GEN_RAW_SPEC_000084
   * @tc.desc Verify parse declaration for PRI_void.GEN.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.RAW.SPEC.V0
   */
  it('testParse_PRI_void_GEN_RAW_SPEC_000084', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_ARR1_NORM_000085
   * @tc.name testParse_PRI_void_GEN_ARR1_NORM_000085
   * @tc.desc Verify parse declaration for PRI_void.GEN.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.ARR1.NORM.V0
   */
  it('testParse_PRI_void_GEN_ARR1_NORM_000085', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<void>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_ARR1_BOUND_000086
   * @tc.name testParse_PRI_void_GEN_ARR1_BOUND_000086
   * @tc.desc Verify parse declaration for PRI_void.GEN.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.ARR1.BOUND.V0
   */
  it('testParse_PRI_void_GEN_ARR1_BOUND_000086', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<void>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_ARR1_ERR_000087
   * @tc.name testParse_PRI_void_GEN_ARR1_ERR_000087
   * @tc.desc Verify parse declaration for PRI_void.GEN.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.GEN.ARR1.ERR.V0
   */
  it('testParse_PRI_void_GEN_ARR1_ERR_000087', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.GEN.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_ARR1_SPEC_000088
   * @tc.name testParse_PRI_void_GEN_ARR1_SPEC_000088
   * @tc.desc Verify parse declaration for PRI_void.GEN.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.ARR1.SPEC.V0
   */
  it('testParse_PRI_void_GEN_ARR1_SPEC_000088', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends Array<void>>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_PROM_NORM_000089
   * @tc.name testParse_PRI_void_GEN_PROM_NORM_000089
   * @tc.desc Verify parse declaration for PRI_void.GEN.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.PROM.NORM.V0
   */
  it('testParse_PRI_void_GEN_PROM_NORM_000089', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_PROM_BOUND_000090
   * @tc.name testParse_PRI_void_GEN_PROM_BOUND_000090
   * @tc.desc Verify parse declaration for PRI_void.GEN.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.PROM.BOUND.V0
   */
  it('testParse_PRI_void_GEN_PROM_BOUND_000090', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_PROM_ERR_000091
   * @tc.name testParse_PRI_void_GEN_PROM_ERR_000091
   * @tc.desc Verify parse declaration for PRI_void.GEN.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.GEN.PROM.ERR.V0
   */
  it('testParse_PRI_void_GEN_PROM_ERR_000091', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.GEN.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_GEN_PROM_SPEC_000092
   * @tc.name testParse_PRI_void_GEN_PROM_SPEC_000092
   * @tc.desc Verify parse declaration for PRI_void.GEN.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.GEN.PROM.SPEC.V0
   */
  it('testParse_PRI_void_GEN_PROM_SPEC_000092', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Gen<T extends number>(x: T): T { return x; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_GEN_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.GEN.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.GEN.PROM.SPEC.V0");
  });

});
