/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_void_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_RAW_NORM_000049
   * @tc.name testParse_PRI_void_RET_RAW_NORM_000049
   * @tc.desc Verify parse declaration for PRI_void.RET.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.RAW.NORM.V0
   */
  it('testParse_PRI_void_RET_RAW_NORM_000049', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_RAW_BOUND_000050
   * @tc.name testParse_PRI_void_RET_RAW_BOUND_000050
   * @tc.desc Verify parse declaration for PRI_void.RET.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.RAW.BOUND.V0
   */
  it('testParse_PRI_void_RET_RAW_BOUND_000050', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_RAW_ERR_000051
   * @tc.name testParse_PRI_void_RET_RAW_ERR_000051
   * @tc.desc Verify parse declaration for PRI_void.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.RET.RAW.ERR.V0
   */
  it('testParse_PRI_void_RET_RAW_ERR_000051', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_RAW_SPEC_000052
   * @tc.name testParse_PRI_void_RET_RAW_SPEC_000052
   * @tc.desc Verify parse declaration for PRI_void.RET.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.RAW.SPEC.V0
   */
  it('testParse_PRI_void_RET_RAW_SPEC_000052', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_ARR1_NORM_000053
   * @tc.name testParse_PRI_void_RET_ARR1_NORM_000053
   * @tc.desc Verify parse declaration for PRI_void.RET.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.ARR1.NORM.V0
   */
  it('testParse_PRI_void_RET_ARR1_NORM_000053', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_ARR1_BOUND_000054
   * @tc.name testParse_PRI_void_RET_ARR1_BOUND_000054
   * @tc.desc Verify parse declaration for PRI_void.RET.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.ARR1.BOUND.V0
   */
  it('testParse_PRI_void_RET_ARR1_BOUND_000054', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_ARR1_ERR_000055
   * @tc.name testParse_PRI_void_RET_ARR1_ERR_000055
   * @tc.desc Verify parse declaration for PRI_void.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.RET.ARR1.ERR.V0
   */
  it('testParse_PRI_void_RET_ARR1_ERR_000055', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_ARR1_SPEC_000056
   * @tc.name testParse_PRI_void_RET_ARR1_SPEC_000056
   * @tc.desc Verify parse declaration for PRI_void.RET.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.ARR1.SPEC.V0
   */
  it('testParse_PRI_void_RET_ARR1_SPEC_000056', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<void> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_NULLU_NORM_000057
   * @tc.name testParse_PRI_void_RET_NULLU_NORM_000057
   * @tc.desc Verify parse declaration for PRI_void.RET.NULLU.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.NULLU.NORM.V0
   */
  it('testParse_PRI_void_RET_NULLU_NORM_000057', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_NULLU_BOUND_000058
   * @tc.name testParse_PRI_void_RET_NULLU_BOUND_000058
   * @tc.desc Verify parse declaration for PRI_void.RET.NULLU.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.NULLU.BOUND.V0
   */
  it('testParse_PRI_void_RET_NULLU_BOUND_000058', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_NULLU_ERR_000059
   * @tc.name testParse_PRI_void_RET_NULLU_ERR_000059
   * @tc.desc Verify parse declaration for PRI_void.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.RET.NULLU.ERR.V0
   */
  it('testParse_PRI_void_RET_NULLU_ERR_000059', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_NULLU_SPEC_000060
   * @tc.name testParse_PRI_void_RET_NULLU_SPEC_000060
   * @tc.desc Verify parse declaration for PRI_void.RET.NULLU.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.NULLU.SPEC.V0
   */
  it('testParse_PRI_void_RET_NULLU_SPEC_000060', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_PROM_NORM_000061
   * @tc.name testParse_PRI_void_RET_PROM_NORM_000061
   * @tc.desc Verify parse declaration for PRI_void.RET.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.PROM.NORM.V0
   */
  it('testParse_PRI_void_RET_PROM_NORM_000061', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_PROM_BOUND_000062
   * @tc.name testParse_PRI_void_RET_PROM_BOUND_000062
   * @tc.desc Verify parse declaration for PRI_void.RET.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.PROM.BOUND.V0
   */
  it('testParse_PRI_void_RET_PROM_BOUND_000062', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_PROM_ERR_000063
   * @tc.name testParse_PRI_void_RET_PROM_ERR_000063
   * @tc.desc Verify parse declaration for PRI_void.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.RET.PROM.ERR.V0
   */
  it('testParse_PRI_void_RET_PROM_ERR_000063', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_RET_PROM_SPEC_000064
   * @tc.name testParse_PRI_void_RET_PROM_SPEC_000064
   * @tc.desc Verify parse declaration for PRI_void.RET.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.RET.PROM.SPEC.V0
   */
  it('testParse_PRI_void_RET_PROM_SPEC_000064', function () {
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): void { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_void.RET.PROM.SPEC.V0");
  });

});
