/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';

describe('SuiteV3_P_pri_void_as_typealias', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_RAW_NORM_000065
   * @tc.name testParse_PRI_void_TAL_RAW_NORM_000065
   * @tc.desc Verify parse declaration for PRI_void.TAL.RAW.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.RAW.NORM.V0
   */
  it('testParse_PRI_void_TAL_RAW_NORM_000065', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_RAW_BOUND_000066
   * @tc.name testParse_PRI_void_TAL_RAW_BOUND_000066
   * @tc.desc Verify parse declaration for PRI_void.TAL.RAW.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.RAW.BOUND.V0
   */
  it('testParse_PRI_void_TAL_RAW_BOUND_000066', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_RAW_ERR_000067
   * @tc.name testParse_PRI_void_TAL_RAW_ERR_000067
   * @tc.desc Verify parse declaration for PRI_void.TAL.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.TAL.RAW.ERR.V0
   */
  it('testParse_PRI_void_TAL_RAW_ERR_000067', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_RAW_SPEC_000068
   * @tc.name testParse_PRI_void_TAL_RAW_SPEC_000068
   * @tc.desc Verify parse declaration for PRI_void.TAL.RAW.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.RAW.SPEC.V0
   */
  it('testParse_PRI_void_TAL_RAW_SPEC_000068', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.RAW.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_ARR1_NORM_000069
   * @tc.name testParse_PRI_void_TAL_ARR1_NORM_000069
   * @tc.desc Verify parse declaration for PRI_void.TAL.ARR1.NORM.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.ARR1.NORM.V0
   */
  it('testParse_PRI_void_TAL_ARR1_NORM_000069', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_ARR1_BOUND_000070
   * @tc.name testParse_PRI_void_TAL_ARR1_BOUND_000070
   * @tc.desc Verify parse declaration for PRI_void.TAL.ARR1.BOUND.V0 input="std::vector<void>" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.ARR1.BOUND.V0
   */
  it('testParse_PRI_void_TAL_ARR1_BOUND_000070', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_ARR1_ERR_000071
   * @tc.name testParse_PRI_void_TAL_ARR1_ERR_000071
   * @tc.desc Verify parse declaration for PRI_void.TAL.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1177537132__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.TAL.ARR1.ERR.V0
   */
  it('testParse_PRI_void_TAL_ARR1_ERR_000071', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_ARR1_SPEC_000072
   * @tc.name testParse_PRI_void_TAL_ARR1_SPEC_000072
   * @tc.desc Verify parse declaration for PRI_void.TAL.ARR1.SPEC.V0 input="std::vector< void >" expect="Array<void>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.ARR1.SPEC.V0
   */
  it('testParse_PRI_void_TAL_ARR1_SPEC_000072', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = Array<void>;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.ARR1.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_NULLU_NORM_000073
   * @tc.name testParse_PRI_void_TAL_NULLU_NORM_000073
   * @tc.desc Verify parse declaration for PRI_void.TAL.NULLU.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.NULLU.NORM.V0
   */
  it('testParse_PRI_void_TAL_NULLU_NORM_000073', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_NULLU_BOUND_000074
   * @tc.name testParse_PRI_void_TAL_NULLU_BOUND_000074
   * @tc.desc Verify parse declaration for PRI_void.TAL.NULLU.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.NULLU.BOUND.V0
   */
  it('testParse_PRI_void_TAL_NULLU_BOUND_000074', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_NULLU_ERR_000075
   * @tc.name testParse_PRI_void_TAL_NULLU_ERR_000075
   * @tc.desc Verify parse declaration for PRI_void.TAL.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.TAL.NULLU.ERR.V0
   */
  it('testParse_PRI_void_TAL_NULLU_ERR_000075', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_NULLU_SPEC_000076
   * @tc.name testParse_PRI_void_TAL_NULLU_SPEC_000076
   * @tc.desc Verify parse declaration for PRI_void.TAL.NULLU.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.NULLU.SPEC.V0
   */
  it('testParse_PRI_void_TAL_NULLU_SPEC_000076', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.NULLU.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_PROM_NORM_000077
   * @tc.name testParse_PRI_void_TAL_PROM_NORM_000077
   * @tc.desc Verify parse declaration for PRI_void.TAL.PROM.NORM.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.PROM.NORM.V0
   */
  it('testParse_PRI_void_TAL_PROM_NORM_000077', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.NORM.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_PROM_BOUND_000078
   * @tc.name testParse_PRI_void_TAL_PROM_BOUND_000078
   * @tc.desc Verify parse declaration for PRI_void.TAL.PROM.BOUND.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.PROM.BOUND.V0
   */
  it('testParse_PRI_void_TAL_PROM_BOUND_000078', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.BOUND.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_PROM_ERR_000079
   * @tc.name testParse_PRI_void_TAL_PROM_ERR_000079
   * @tc.desc Verify parse declaration for PRI_void.TAL.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3625364__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair G-PRI_void.TAL.PROM.ERR.V0
   */
  it('testParse_PRI_void_TAL_PROM_ERR_000079', function () {
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_void.TAL.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_PARSE_PRI_void_TAL_PROM_SPEC_000080
   * @tc.name testParse_PRI_void_TAL_PROM_SPEC_000080
   * @tc.desc Verify parse declaration for PRI_void.TAL.PROM.SPEC.V0 input="void" expect="void"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair G-PRI_void.TAL.PROM.SPEC.V0
   */
  it('testParse_PRI_void_TAL_PROM_SPEC_000080', function () {
    // step1: 构造待解析源码
    const src = "export type NapiV2Alias = void;\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_void_TAL_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_void.TAL.PROM.SPEC.V0 parse null");
    // step4: 校验 type alias 存在
    assert.ok(res.types && res.types.length >= 1, "P TAL PRI_void.TAL.PROM.SPEC.V0");
  });

});
