/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_bool_as_field', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RAW_NORM_000093
   * @tc.name testInteg_PRI_bool_FLD_RAW_NORM_000093
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RAW.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RAW.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_RAW_NORM_000093', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RAW.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RAW.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RAW.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RAW.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RAW.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RAW_BOUND_000094
   * @tc.name testInteg_PRI_bool_FLD_RAW_BOUND_000094
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RAW.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RAW.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_RAW_BOUND_000094', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RAW.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RAW.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RAW.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RAW.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RAW.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RAW_ERR_000095
   * @tc.name testInteg_PRI_bool_FLD_RAW_ERR_000095
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.RAW.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_RAW_ERR_000095', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RAW_SPEC_000096
   * @tc.name testInteg_PRI_bool_FLD_RAW_SPEC_000096
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RAW.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RAW.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_RAW_SPEC_000096', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RAW.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RAW.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RAW.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RAW.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RAW.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_OPT_NORM_000097
   * @tc.name testInteg_PRI_bool_FLD_OPT_NORM_000097
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.OPT.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.OPT.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_OPT_NORM_000097', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.OPT.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_OPT_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.OPT.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.OPT.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.OPT.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.OPT.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.OPT.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_OPT_BOUND_000098
   * @tc.name testInteg_PRI_bool_FLD_OPT_BOUND_000098
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.OPT.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.OPT.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_OPT_BOUND_000098', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.OPT.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_OPT_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.OPT.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.OPT.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.OPT.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.OPT.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.OPT.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_OPT_ERR_000099
   * @tc.name testInteg_PRI_bool_FLD_OPT_ERR_000099
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.OPT.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.OPT.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_OPT_ERR_000099', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.OPT.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_OPT_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.OPT.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_OPT_SPEC_000100
   * @tc.name testInteg_PRI_bool_FLD_OPT_SPEC_000100
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.OPT.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.OPT.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_OPT_SPEC_000100', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.OPT.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v?: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_OPT_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.OPT.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.OPT.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.OPT.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.OPT.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.OPT.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RO_NORM_000101
   * @tc.name testInteg_PRI_bool_FLD_RO_NORM_000101
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RO.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RO.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_RO_NORM_000101', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RO.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RO_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RO.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RO.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RO.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RO.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RO.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RO_BOUND_000102
   * @tc.name testInteg_PRI_bool_FLD_RO_BOUND_000102
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RO.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RO.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_RO_BOUND_000102', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RO.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RO_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RO.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RO.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RO.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RO.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RO.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RO_ERR_000103
   * @tc.name testInteg_PRI_bool_FLD_RO_ERR_000103
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RO.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.RO.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_RO_ERR_000103', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.RO.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RO_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.RO.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_RO_SPEC_000104
   * @tc.name testInteg_PRI_bool_FLD_RO_SPEC_000104
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.RO.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.RO.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_RO_SPEC_000104', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.RO.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_RO_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.RO.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.RO.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.RO.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.RO.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.RO.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PTR_NORM_000105
   * @tc.name testInteg_PRI_bool_FLD_PTR_NORM_000105
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PTR.NORM.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PTR.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_PTR_NORM_000105', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PTR.NORM.V0 input=bool*");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PTR.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PTR.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PTR.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PTR.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool*");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PTR_BOUND_000106
   * @tc.name testInteg_PRI_bool_FLD_PTR_BOUND_000106
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PTR.BOUND.V0 input="bool *" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PTR.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_PTR_BOUND_000106', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool *";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PTR.BOUND.V0 input=bool *");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PTR.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PTR.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PTR.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PTR.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool *");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PTR_ERR_000107
   * @tc.name testInteg_PRI_bool_FLD_PTR_ERR_000107
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.PTR.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_PTR_ERR_000107', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.PTR.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PTR_SPEC_000108
   * @tc.name testInteg_PRI_bool_FLD_PTR_SPEC_000108
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PTR.SPEC.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PTR.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_PTR_SPEC_000108', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PTR.SPEC.V0 input=bool*");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PTR.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PTR.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PTR.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PTR.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool*");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_ARR1_NORM_000109
   * @tc.name testInteg_PRI_bool_FLD_ARR1_NORM_000109
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.ARR1.NORM.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.ARR1.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_ARR1_NORM_000109', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<bool>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.FLD.ARR1.NORM.V0 input=std::vector<bool>");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<boolean>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.ARR1.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.ARR1.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.ARR1.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<boolean>" || t.includes("Array"), "P FLD PRI_bool.FLD.ARR1.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<bool>");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.FLD.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_ARR1_BOUND_000110
   * @tc.name testInteg_PRI_bool_FLD_ARR1_BOUND_000110
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.ARR1.BOUND.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.ARR1.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_ARR1_BOUND_000110', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<bool>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.FLD.ARR1.BOUND.V0 input=std::vector<bool>");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<boolean>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.ARR1.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.ARR1.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.ARR1.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<boolean>" || t.includes("Array"), "P FLD PRI_bool.FLD.ARR1.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<bool>");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.FLD.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_ARR1_ERR_000111
   * @tc.name testInteg_PRI_bool_FLD_ARR1_ERR_000111
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1196001538__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.ARR1.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_ARR1_ERR_000111', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_1196001538__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_ARR1_SPEC_000112
   * @tc.name testInteg_PRI_bool_FLD_ARR1_SPEC_000112
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.ARR1.SPEC.V0 input="std::vector< bool >" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.ARR1.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_ARR1_SPEC_000112', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< bool >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.FLD.ARR1.SPEC.V0 input=std::vector< bool >");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: Array<boolean>; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.ARR1.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.ARR1.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.ARR1.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "Array<boolean>" || t.includes("Array"), "P FLD PRI_bool.FLD.ARR1.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< bool >");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.FLD.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_NULLU_NORM_000113
   * @tc.name testInteg_PRI_bool_FLD_NULLU_NORM_000113
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.NULLU.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.NULLU.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_NULLU_NORM_000113', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.NULLU.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.NULLU.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.NULLU.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.NULLU.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.NULLU.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_NULLU_BOUND_000114
   * @tc.name testInteg_PRI_bool_FLD_NULLU_BOUND_000114
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.NULLU.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.NULLU.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_NULLU_BOUND_000114', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.NULLU.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.NULLU.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.NULLU.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.NULLU.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.NULLU.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_NULLU_ERR_000115
   * @tc.name testInteg_PRI_bool_FLD_NULLU_ERR_000115
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.NULLU.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_NULLU_ERR_000115', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_NULLU_SPEC_000116
   * @tc.name testInteg_PRI_bool_FLD_NULLU_SPEC_000116
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.NULLU.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.NULLU.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_NULLU_SPEC_000116', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.NULLU.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.NULLU.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.NULLU.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.NULLU.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.NULLU.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PROM_NORM_000117
   * @tc.name testInteg_PRI_bool_FLD_PROM_NORM_000117
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PROM.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PROM.NORM.V0
   */
  it('testInteg_PRI_bool_FLD_PROM_NORM_000117', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PROM.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PROM.NORM.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PROM.NORM.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PROM.NORM.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PROM.NORM.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PROM_BOUND_000118
   * @tc.name testInteg_PRI_bool_FLD_PROM_BOUND_000118
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PROM.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PROM.BOUND.V0
   */
  it('testInteg_PRI_bool_FLD_PROM_BOUND_000118', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PROM.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PROM.BOUND.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PROM.BOUND.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PROM.BOUND.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PROM.BOUND.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PROM_ERR_000119
   * @tc.name testInteg_PRI_bool_FLD_PROM_ERR_000119
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.FLD.PROM.ERR.V0
   */
  it('testInteg_PRI_bool_FLD_PROM_ERR_000119', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.FLD.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.FLD.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_FLD_PROM_SPEC_000120
   * @tc.name testInteg_PRI_bool_FLD_PROM_SPEC_000120
   * @tc.desc Verify roundtrip parse+map for PRI_bool.FLD.PROM.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.FLD.PROM.SPEC.V0
   */
  it('testInteg_PRI_bool_FLD_PROM_SPEC_000120', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.FLD.PROM.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Cls { v: boolean; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_FLD_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.FLD.PROM.SPEC.V0 parse null");
    // step4: 校验字段类型
    assert.ok(res.classes && res.classes.length >= 1, "P FLD classes PRI_bool.FLD.PROM.SPEC.V0");
    const t = res.classes[0].variableList[0].type;
    assert.ok(typeof t === 'string' && t.length > 0, "P FLD type PRI_bool.FLD.PROM.SPEC.V0");
    assert.ok(t.replace(/\s+/g, '') === "boolean" || t.includes("boolean"), "P FLD PRI_bool.FLD.PROM.SPEC.V0" + ' got=' + t);
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.FLD.PROM.SPEC.V0");
  });

});
