/* Auto-generated by suite_v3/tools/generate.ts — do not edit */
import * as assert from 'assert';
import { doParseTs } from '../../../../../parse/parsets';
import { transTskey2Ckey } from '../../../../../gen/gendts';

describe('SuiteV3_I_pri_bool_as_return', function () {
  this.timeout(30000);

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_RAW_NORM_000149
   * @tc.name testInteg_PRI_bool_RET_RAW_NORM_000149
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.RAW.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.RAW.NORM.V0
   */
  it('testInteg_PRI_bool_RET_RAW_NORM_000149', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.RAW.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.RAW.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_RAW_BOUND_000150
   * @tc.name testInteg_PRI_bool_RET_RAW_BOUND_000150
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.RAW.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.RAW.BOUND.V0
   */
  it('testInteg_PRI_bool_RET_RAW_BOUND_000150', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.RAW.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.RAW.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_RAW_ERR_000151
   * @tc.name testInteg_PRI_bool_RET_RAW_ERR_000151
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.RAW.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.RET.RAW.ERR.V0
   */
  it('testInteg_PRI_bool_RET_RAW_ERR_000151', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.RET.RAW.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.RAW.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_RAW_SPEC_000152
   * @tc.name testInteg_PRI_bool_RET_RAW_SPEC_000152
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.RAW.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.RAW.SPEC.V0
   */
  it('testInteg_PRI_bool_RET_RAW_SPEC_000152', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.RAW.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_RAW_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.RAW.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.RAW.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.RAW.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PTR_NORM_000153
   * @tc.name testInteg_PRI_bool_RET_PTR_NORM_000153
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PTR.NORM.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PTR.NORM.V0
   */
  it('testInteg_PRI_bool_RET_PTR_NORM_000153', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PTR.NORM.V0 input=bool*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool*");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PTR.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PTR_BOUND_000154
   * @tc.name testInteg_PRI_bool_RET_PTR_BOUND_000154
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PTR.BOUND.V0 input="bool *" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PTR.BOUND.V0
   */
  it('testInteg_PRI_bool_RET_PTR_BOUND_000154', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool *";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PTR.BOUND.V0 input=bool *");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool *");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PTR.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PTR_ERR_000155
   * @tc.name testInteg_PRI_bool_RET_PTR_ERR_000155
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PTR.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.RET.PTR.ERR.V0
   */
  it('testInteg_PRI_bool_RET_PTR_ERR_000155', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.RET.PTR.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.PTR.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PTR_SPEC_000156
   * @tc.name testInteg_PRI_bool_RET_PTR_SPEC_000156
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PTR.SPEC.V0 input="bool*" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PTR.SPEC.V0
   */
  it('testInteg_PRI_bool_RET_PTR_SPEC_000156', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool*";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PTR.SPEC.V0 input=bool*");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PTR_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PTR.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PTR.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool*");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PTR.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_ARR1_NORM_000157
   * @tc.name testInteg_PRI_bool_RET_ARR1_NORM_000157
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.ARR1.NORM.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.ARR1.NORM.V0
   */
  it('testInteg_PRI_bool_RET_ARR1_NORM_000157', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<bool>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.RET.ARR1.NORM.V0 input=std::vector<bool>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<bool>");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.RET.ARR1.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_ARR1_BOUND_000158
   * @tc.name testInteg_PRI_bool_RET_ARR1_BOUND_000158
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.ARR1.BOUND.V0 input="std::vector<bool>" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.ARR1.BOUND.V0
   */
  it('testInteg_PRI_bool_RET_ARR1_BOUND_000158', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector<bool>";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.RET.ARR1.BOUND.V0 input=std::vector<bool>");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector<bool>");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.RET.ARR1.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_ARR1_ERR_000159
   * @tc.name testInteg_PRI_bool_RET_ARR1_ERR_000159
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.ARR1.ERR.V0 input="__INVALID_TYPE_TOKEN_1196001538__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.RET.ARR1.ERR.V0
   */
  it('testInteg_PRI_bool_RET_ARR1_ERR_000159', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_1196001538__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.RET.ARR1.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.ARR1.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_ARR1_SPEC_000160
   * @tc.name testInteg_PRI_bool_RET_ARR1_SPEC_000160
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.ARR1.SPEC.V0 input="std::vector< bool >" expect="Array<boolean>"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.ARR1.SPEC.V0
   */
  it('testInteg_PRI_bool_RET_ARR1_SPEC_000160', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "std::vector< bool >";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "Array<boolean>", "G PRI_bool.RET.ARR1.SPEC.V0 input=std::vector< bool >");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): Array<boolean> { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_ARR1_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.ARR1.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.ARR1.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("std::vector< bool >");
    assert.strictEqual(mapped, "Array<boolean>", "I map==expect PRI_bool.RET.ARR1.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_NULLU_NORM_000161
   * @tc.name testInteg_PRI_bool_RET_NULLU_NORM_000161
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.NULLU.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.NULLU.NORM.V0
   */
  it('testInteg_PRI_bool_RET_NULLU_NORM_000161', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.NULLU.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.NULLU.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_NULLU_BOUND_000162
   * @tc.name testInteg_PRI_bool_RET_NULLU_BOUND_000162
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.NULLU.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.NULLU.BOUND.V0
   */
  it('testInteg_PRI_bool_RET_NULLU_BOUND_000162', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.NULLU.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.NULLU.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_NULLU_ERR_000163
   * @tc.name testInteg_PRI_bool_RET_NULLU_ERR_000163
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.NULLU.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.RET.NULLU.ERR.V0
   */
  it('testInteg_PRI_bool_RET_NULLU_ERR_000163', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.RET.NULLU.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.NULLU.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_NULLU_SPEC_000164
   * @tc.name testInteg_PRI_bool_RET_NULLU_SPEC_000164
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.NULLU.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.NULLU.SPEC.V0
   */
  it('testInteg_PRI_bool_RET_NULLU_SPEC_000164', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.NULLU.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_NULLU_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.NULLU.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.NULLU.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.NULLU.SPEC.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PROM_NORM_000165
   * @tc.name testInteg_PRI_bool_RET_PROM_NORM_000165
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PROM.NORM.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PROM.NORM.V0
   */
  it('testInteg_PRI_bool_RET_PROM_NORM_000165', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PROM.NORM.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_NORM_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.NORM.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.NORM.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PROM.NORM.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PROM_BOUND_000166
   * @tc.name testInteg_PRI_bool_RET_PROM_BOUND_000166
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PROM.BOUND.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PROM.BOUND.V0
   */
  it('testInteg_PRI_bool_RET_PROM_BOUND_000166', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PROM.BOUND.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_BOUND_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.BOUND.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.BOUND.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PROM.BOUND.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PROM_ERR_000167
   * @tc.name testInteg_PRI_bool_RET_PROM_ERR_000167
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PROM.ERR.V0 input="__INVALID_TYPE_TOKEN_3029738__" expect="any"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 2
   * @pair P+G-PRI_bool.RET.PROM.ERR.V0
   */
  it('testInteg_PRI_bool_RET_PROM_ERR_000167', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "__INVALID_TYPE_TOKEN_3029738__";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 负向期望 any
    assert.strictEqual(actual, 'any', "G negative PRI_bool.RET.PROM.ERR.V0");
    // [P]
    // step1: 构造待解析源码
    const src = "export class NapiV2Neg { v: any; }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_ERR_V0.ts", src);
    // step3: 负向 — 解析不崩溃且返回 classes
    assert.ok(res && Array.isArray(res.classes), "P neg PRI_bool.RET.PROM.ERR.V0");
  });

  /**
   * @tc.number SUB_NAPI_INTEG_PRI_bool_RET_PROM_SPEC_000168
   * @tc.name testInteg_PRI_bool_RET_PROM_SPEC_000168
   * @tc.desc Verify roundtrip parse+map for PRI_bool.RET.PROM.SPEC.V0 input="bool" expect="boolean"
   * @tc.size MediumTest
   * @tc.type Function
   * @tc.level Level 1
   * @pair P+G-PRI_bool.RET.PROM.SPEC.V0
   */
  it('testInteg_PRI_bool_RET_PROM_SPEC_000168', function () {
    // --- 集成：先映射，再解析，再交叉校验 ---
    // [G]
    // step1: 输入 C/声明类型
    const inputType = "bool";
    // step2: 映射为 TS 类型
    const actual = transTskey2Ckey(inputType);
    // step3: 断言映射结果
    assert.strictEqual(actual, "boolean", "G PRI_bool.RET.PROM.SPEC.V0 input=bool");
    // [P]
    // step1: 构造待解析源码
    const src = "export function napiV2Ret(): boolean { throw new Error('x'); }\n";
    // step2: 调用解析
    const res = doParseTs("v3_PRI_bool_RET_PROM_SPEC_V0.ts", src);
    // step3: 解析结果非空
    assert.ok(res, "P PRI_bool.RET.PROM.SPEC.V0 parse null");
    // step4: 校验函数声明存在
    assert.ok(res.funcs && res.funcs.length >= 1, "P func PRI_bool.RET.PROM.SPEC.V0");
    // [I] map 与 expect 一致
    const mapped = transTskey2Ckey("bool");
    assert.strictEqual(mapped, "boolean", "I map==expect PRI_bool.RET.PROM.SPEC.V0");
  });

});
