/*
 * Copyright (c) 2024 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 将 T_cross 落盘为 commonlibrary 风格物理 it：
 * 每条独立 it + @tc.* 注释 + 逐步展开的断言体（禁止 runXxxCase 封装）。
 *
 * 子集（默认 LIMIT=300）：src/test/suite_v3/{parse,gen,integration}/types/...
 * 全量：src/test/suite_v3/bulk/... 与 out/test/suite_v3/bulk/...（.js，gitignore）
 *
 * 用法：node ./out/test/suite_v3/tools/generate.js
 * 环境：SUITE_V3_GENERATE_LIMIT=N|all|0 ；SUITE_V3_FULL=1 / --full 写 bulk
 */

import * as fs from 'fs';
import * as path from 'path';
import { getTCross } from '../../suite_v2/catalog/expand';
import { ContextId, Scenario, SuiteKind } from '../../suite_v2/catalog/types';
import { buildTcMeta, formatTcComment } from '../harness/tc_meta';
import { SUITE_V3_DEFAULT_LIMIT, SUITE_V3_MAX_IT_PER_FILE } from '../constants';
import { emitCaseBody, needsGen, needsParse } from './emit_body';

const CONTEXT_FILE: Record<ContextId, string> = {
  FLD: 'as_field',
  PAR: 'as_param',
  RET: 'as_return',
  TAL: 'as_typealias',
  GEN: 'as_generic',
};

const SUITE_DIR: Record<SuiteKind, string> = {
  P: 'parse',
  G: 'gen',
  I: 'integration',
};

const EXT_SUFFIX: Record<SuiteKind, string> = {
  P: 'p',
  G: 'g',
  I: 'i',
};

function srcRoot(): string {
  return path.resolve(__dirname, '../../../../src/test/suite_v3');
}

function outRoot(): string {
  return path.resolve(__dirname, '..');
}

function bucketOf(sc: Scenario): string {
  if (sc.family === 'C2') {
    if (sc.typeId.startsWith('C2_vec_map')) {
      return 'c2_vec_map';
    }
    if (sc.typeId.startsWith('C2_set_vec')) {
      return 'c2_set_vec';
    }
    if (sc.typeId.startsWith('C2_pair')) {
      return 'c2_pair';
    }
    return 'c2_other';
  }
  if (sc.family === 'CTR') {
    const m = /^CTR_([A-Za-z0-9]+)/.exec(sc.typeId);
    return m ? `ctr_${m[1].toLowerCase()}` : 'ctr_other';
  }
  const id = sc.typeId
    .replace(/^PRI_/i, 'pri_')
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return id || 'pri_other';
}

function rmDirIfExists(dir: string): void {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function ensureEmptyDir(dir: string): void {
  rmDirIfExists(dir);
  fs.mkdirSync(dir, { recursive: true });
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

interface CaseItem {
  sc: Scenario;
  index: number;
}

function emitTsImports(suiteKind: SuiteKind): string[] {
  const lines = [
    `/* Auto-generated by suite_v3/tools/generate.ts — do not edit */`,
    `import * as assert from 'assert';`,
  ];
  // types/{bucket}/file → ../../../../../parse|gen
  if (needsParse(suiteKind)) {
    lines.push(`import { doParseTs } from '../../../../../parse/parsets';`);
  }
  if (needsGen(suiteKind)) {
    lines.push(`import { transTskey2Ckey } from '../../../../../gen/gendts';`);
  }
  lines.push('');
  return lines;
}

function emitJsImports(suiteKind: SuiteKind, depthToSrcOut: string): string[] {
  // depthToSrcOut: relative from file to out/ (where parse/ and gen/ live)
  const lines = [
    `/* Auto-generated by suite_v3/tools/generate.ts — do not edit */`,
    `const assert = require('assert');`,
  ];
  if (needsParse(suiteKind)) {
    lines.push(`const { doParseTs } = require('${depthToSrcOut}/parse/parsets');`);
  }
  if (needsGen(suiteKind)) {
    lines.push(`const { transTskey2Ckey } = require('${depthToSrcOut}/gen/gendts');`);
  }
  lines.push('');
  return lines;
}

function emitCases(suiteKind: SuiteKind, suiteTitle: string, cases: CaseItem[]): string[] {
  const lines: string[] = [];
  lines.push(`describe('${suiteTitle}', function () {`);
  lines.push(`  this.timeout(30000);`);
  lines.push('');

  for (const { sc, index } of cases) {
    const meta = buildTcMeta(suiteKind, sc, index);
    const safeName = escapeStr(meta.name);
    const comment = formatTcComment(meta)
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    lines.push(comment);
    lines.push(`  it('${safeName}', function () {`);
    lines.push(...emitCaseBody(suiteKind, sc, '    '));
    lines.push(`  });`);
    lines.push('');
  }

  lines.push(`});`);
  lines.push('');
  return lines;
}

function emitTsFile(
  filePath: string,
  suiteKind: SuiteKind,
  suiteTitle: string,
  cases: CaseItem[]
): void {
  const lines = [...emitTsImports(suiteKind), ...emitCases(suiteKind, suiteTitle, cases)];
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

function emitJsFile(
  filePath: string,
  suiteKind: SuiteKind,
  suiteTitle: string,
  cases: CaseItem[],
  depthToOutRoot: string
): void {
  const lines = [...emitJsImports(suiteKind, depthToOutRoot), ...emitCases(suiteKind, suiteTitle, cases)];
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

function writeGrouped(
  suiteKind: SuiteKind,
  all: Scenario[],
  opts: { mode: 'sample' | 'bulk' }
): { files: number; cases: number } {
  const dirName = SUITE_DIR[suiteKind];
  const suffix = EXT_SUFFIX[suiteKind];
  const groups = new Map<string, CaseItem[]>();

  all.forEach((sc, index) => {
    const bucket = bucketOf(sc);
    const base = CONTEXT_FILE[sc.context];
    const key = `${bucket}::${base}`;
    if (!groups.has(key)) {
      groups.set(key, []);
    }
    groups.get(key)!.push({ sc, index });
  });

  let files = 0;
  let cases = 0;

  for (const [key, list] of groups) {
    const [bucket, base] = key.split('::');
    for (let i = 0; i < list.length; i += SUITE_V3_MAX_IT_PER_FILE) {
      const slice = list.slice(i, i + SUITE_V3_MAX_IT_PER_FILE);
      const part =
        list.length > SUITE_V3_MAX_IT_PER_FILE
          ? `_${String(Math.floor(i / SUITE_V3_MAX_IT_PER_FILE) + 1).padStart(2, '0')}`
          : '';
      const fileName = `${base}${part}.${suffix}.test.${opts.mode === 'sample' ? 'ts' : 'js'}`;
      const suiteTitle = `SuiteV3_${suiteKind}_${bucket}_${base}${part}`;

      if (opts.mode === 'sample') {
        const fp = path.join(srcRoot(), dirName, 'types', bucket, fileName);
        emitTsFile(fp, suiteKind, suiteTitle, slice);
      } else {
        const rel = path.join('bulk', dirName, 'types', bucket, fileName);
        // bulk/parse/types/bucket → ../../../../../../ 到 out/
        const depthToOut = '../../../../../../';
        emitJsFile(path.join(srcRoot(), rel), suiteKind, suiteTitle, slice, depthToOut);
        emitJsFile(path.join(outRoot(), rel), suiteKind, suiteTitle, slice, depthToOut);
      }
      files += 1;
      cases += slice.length;
    }
  }

  return { files, cases };
}

function wantFull(): boolean {
  return process.env.SUITE_V3_FULL === '1' || process.argv.includes('--full');
}

function resolveLimit(total: number): number {
  const raw = process.env.SUITE_V3_GENERATE_LIMIT;
  if (wantFull()) {
    return total;
  }
  if (!raw || raw === '') {
    return Math.min(SUITE_V3_DEFAULT_LIMIT, total);
  }
  if (raw === 'all' || raw === '0') {
    return total;
  }
  const n = parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 1) {
    return Math.min(SUITE_V3_DEFAULT_LIMIT, total);
  }
  return Math.min(n, total);
}

function main(): void {
  const full = wantFull();
  const mode: 'sample' | 'bulk' = full ? 'bulk' : 'sample';
  const catalog = getTCross();
  const limit = resolveLimit(catalog.length);
  const all = catalog.slice(0, limit);

  console.log(`[suite_v3:generate] mode=${mode} limit=${limit}/${catalog.length}`);

  if (mode === 'sample') {
    for (const d of ['parse', 'gen', 'integration'] as const) {
      ensureEmptyDir(path.join(srcRoot(), d, 'types'));
    }
  } else {
    ensureEmptyDir(path.join(srcRoot(), 'bulk'));
    ensureEmptyDir(path.join(outRoot(), 'bulk'));
  }

  const p = writeGrouped('P', all, { mode });
  const g = writeGrouped('G', all, { mode });
  const i = writeGrouped('I', all, { mode });

  const summary = {
    mode,
    limit,
    catalogTotal: catalog.length,
    P: p.cases,
    G: g.cases,
    I: i.cases,
    total: p.cases + g.cases + i.cases,
    files: p.files + g.files + i.files,
    maxItPerFile: SUITE_V3_MAX_IT_PER_FILE,
    style: 'expanded-inline-it',
    generatedAt: new Date().toISOString(),
  };

  const summaryDir = mode === 'sample' ? srcRoot() : path.join(srcRoot(), 'bulk');
  fs.mkdirSync(summaryDir, { recursive: true });
  fs.writeFileSync(path.join(summaryDir, 'summary.json'), JSON.stringify(summary, null, 2), 'utf8');
  if (mode === 'bulk') {
    fs.writeFileSync(path.join(outRoot(), 'bulk', 'summary.json'), JSON.stringify(summary, null, 2), 'utf8');
  }

  console.log('[suite_v3:generate] wrote', summary);
}

main();
